// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "poly_lift.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic poly_lift::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic poly_lift::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> poly_lift::ap_ST_fsm_state1 = "1";
const sc_lv<21> poly_lift::ap_ST_fsm_state2 = "10";
const sc_lv<21> poly_lift::ap_ST_fsm_state3 = "100";
const sc_lv<21> poly_lift::ap_ST_fsm_state4 = "1000";
const sc_lv<21> poly_lift::ap_ST_fsm_state5 = "10000";
const sc_lv<21> poly_lift::ap_ST_fsm_state6 = "100000";
const sc_lv<21> poly_lift::ap_ST_fsm_state7 = "1000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state8 = "10000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state9 = "100000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state10 = "1000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state11 = "10000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state12 = "100000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<21> poly_lift::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<32> poly_lift::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> poly_lift::ap_const_lv32_4 = "100";
const sc_lv<32> poly_lift::ap_const_lv32_11 = "10001";
const sc_lv<32> poly_lift::ap_const_lv32_1 = "1";
const sc_lv<32> poly_lift::ap_const_lv32_2 = "10";
const sc_lv<32> poly_lift::ap_const_lv32_3 = "11";
const sc_lv<1> poly_lift::ap_const_lv1_0 = "0";
const sc_lv<1> poly_lift::ap_const_lv1_1 = "1";
const sc_lv<32> poly_lift::ap_const_lv32_5 = "101";
const sc_lv<32> poly_lift::ap_const_lv32_8 = "1000";
const sc_lv<32> poly_lift::ap_const_lv32_9 = "1001";
const sc_lv<32> poly_lift::ap_const_lv32_A = "1010";
const sc_lv<32> poly_lift::ap_const_lv32_C = "1100";
const sc_lv<32> poly_lift::ap_const_lv32_D = "1101";
const sc_lv<32> poly_lift::ap_const_lv32_F = "1111";
const sc_lv<32> poly_lift::ap_const_lv32_12 = "10010";
const sc_lv<32> poly_lift::ap_const_lv32_6 = "110";
const sc_lv<10> poly_lift::ap_const_lv10_3 = "11";
const sc_lv<2> poly_lift::ap_const_lv2_0 = "00";
const sc_lv<32> poly_lift::ap_const_lv32_7 = "111";
const sc_lv<32> poly_lift::ap_const_lv32_B = "1011";
const sc_lv<32> poly_lift::ap_const_lv32_E = "1110";
const sc_lv<10> poly_lift::ap_const_lv10_0 = "0000000000";
const sc_lv<32> poly_lift::ap_const_lv32_10 = "10000";
const sc_lv<10> poly_lift::ap_const_lv10_2BC = "1010111100";
const sc_lv<32> poly_lift::ap_const_lv32_13 = "10011";
const sc_lv<64> poly_lift::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> poly_lift::ap_const_lv64_1 = "1";
const sc_lv<64> poly_lift::ap_const_lv64_2 = "10";
const sc_lv<64> poly_lift::ap_const_lv64_2BC = "1010111100";
const sc_lv<32> poly_lift::ap_const_lv32_14 = "10100";
const sc_lv<2> poly_lift::ap_const_lv2_1 = "1";
const sc_lv<10> poly_lift::ap_const_lv10_2BD = "1010111101";
const sc_lv<10> poly_lift::ap_const_lv10_1 = "1";
const sc_lv<2> poly_lift::ap_const_lv2_3 = "11";
const sc_lv<2> poly_lift::ap_const_lv2_2 = "10";
const sc_lv<10> poly_lift::ap_const_lv10_3FD = "1111111101";
const sc_lv<10> poly_lift::ap_const_lv10_3FF = "1111111111";
const sc_lv<10> poly_lift::ap_const_lv10_3FE = "1111111110";
const sc_lv<16> poly_lift::ap_const_lv16_1 = "1";
const sc_lv<3> poly_lift::ap_const_lv3_5 = "101";
const sc_lv<3> poly_lift::ap_const_lv3_7 = "111";
const sc_lv<3> poly_lift::ap_const_lv3_0 = "000";
const sc_lv<13> poly_lift::ap_const_lv13_0 = "0000000000000";
const sc_lv<3> poly_lift::ap_const_lv3_2 = "10";
const bool poly_lift::ap_const_boolean_1 = true;

poly_lift::poly_lift(sc_module_name name) : sc_module(name), mVcdFile(0) {
    b_coeffs_U = new poly_lift_b_coeffs("b_coeffs_U");
    b_coeffs_U->clk(ap_clk);
    b_coeffs_U->reset(ap_rst);
    b_coeffs_U->address0(b_coeffs_address0);
    b_coeffs_U->ce0(b_coeffs_ce0);
    b_coeffs_U->we0(b_coeffs_we0);
    b_coeffs_U->d0(b_coeffs_d0);
    b_coeffs_U->q0(b_coeffs_q0);
    b_coeffs_U->address1(b_coeffs_address1);
    b_coeffs_U->ce1(b_coeffs_ce1);
    b_coeffs_U->we1(b_coeffs_we1);
    b_coeffs_U->d1(b_coeffs_d1);
    b_coeffs_U->q1(b_coeffs_q1);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U23 = new crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1<1,1,16,2,16,16>("crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U23");
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U23->din0(a_coeffs_load_reg_1028);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U23->din1(grp_fu_982_p1);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U23->din2(tmp_2_reg_308);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U23->dout(grp_fu_982_p3);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U24 = new crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1<1,1,16,2,16,16>("crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U24");
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U24->din0(a_coeffs_load_1_reg_1035);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U24->din1(grp_fu_989_p1);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U24->din2(grp_fu_989_p2);
    crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U24->dout(grp_fu_989_p3);
    crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25 = new crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1<1,1,2,3,16,16,16>("crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25");
    crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25->din0(grp_fu_996_p0);
    crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25->din1(ap_var_for_const0);
    crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25->din2(a_coeffs_load_3_reg_1106);
    crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25->din3(reg_392);
    crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25->dout(grp_fu_996_p4);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U26 = new crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1<1,1,2,16,16,16>("crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U26");
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U26->din0(grp_fu_1005_p0);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U26->din1(a_coeffs_load_3_reg_1106);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U26->din2(b_coeffs_load_1_reg_1118);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U26->dout(grp_fu_1005_p3);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U27 = new crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1<1,1,2,16,16,16>("crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U27");
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U27->din0(grp_fu_1012_p0);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U27->din1(a_coeffs_load_3_reg_1106);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U27->din2(b_coeffs_q0);
    crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U27->dout(grp_fu_1012_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_assign_cast_fu_629_p2);
    sensitive << ( tmp_36_fu_579_p3 );
    sensitive << ( tmp_38_fu_587_p1 );

    SC_METHOD(thread_a_assign_fu_623_p2);
    sensitive << ( b_coeffs_q0 );
    sensitive << ( tmp_35_fu_569_p2 );

    SC_METHOD(thread_a_coeffs_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_22_fu_471_p1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_26_fu_504_p1 );

    SC_METHOD(thread_a_coeffs_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_7_fu_416_p1 );
    sensitive << ( tmp_24_fu_493_p1 );

    SC_METHOD(thread_a_coeffs_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_a_coeffs_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_zj_phi_fu_332_p4);
    sensitive << ( zj_reg_328 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_b_coeffs_addr_1_reg_1046);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_b_coeffs_addr_2_reg_1067);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_b_coeffs_addr_reg_1061);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_b_coeffs_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( b_coeffs_addr_1_reg_1046 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( b_coeffs_addr_reg_1061 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( b_coeffs_addr_6_reg_1200 );
    sensitive << ( b_coeffs_addr_7_reg_1229 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_i6_fu_930_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_21_fu_482_p1 );
    sensitive << ( tmp_33_fu_564_p1 );
    sensitive << ( tmp_i7_fu_942_p1 );

    SC_METHOD(thread_b_coeffs_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( b_coeffs_addr_2_reg_1067 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_22_reg_1147 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( exitcond_i_fu_868_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_235_i_fu_947_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_i3_fu_880_p1 );

    SC_METHOD(thread_b_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_i6_fu_930_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_b_coeffs_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( exitcond_i_fu_868_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_b_coeffs_d0);
    sensitive << ( a_coeffs_q1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_fu_396_p2 );
    sensitive << ( tmp_5_reg_1096 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fu_1005_p3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_270_i_fu_861_p2 );
    sensitive << ( tmp_39_i_fu_921_p3 );

    SC_METHOD(thread_b_coeffs_d1);
    sensitive << ( a_coeffs_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( grp_fu_996_p4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_17_reg_1138 );
    sensitive << ( tmp_32_reg_1187 );
    sensitive << ( tmp_s_reg_288 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_9_fu_459_p2 );

    SC_METHOD(thread_b_coeffs_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_b_coeffs_we1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_c_cast_fu_819_p3);
    sensitive << ( tmp_59_fu_811_p3 );

    SC_METHOD(thread_exitcond1_fu_465_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_1_reg_340 );

    SC_METHOD(thread_exitcond2_fu_410_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_reg_317 );

    SC_METHOD(thread_exitcond_fu_552_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( i_2_reg_352 );

    SC_METHOD(thread_exitcond_i_fu_868_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( i_i_reg_363 );

    SC_METHOD(thread_fold1_i_cast_fu_753_p2);
    sensitive << ( tmp_46_fu_737_p2 );
    sensitive << ( tmp_47_fu_743_p4 );

    SC_METHOD(thread_fold2_i_cast_fu_791_p2);
    sensitive << ( fold1_i_cast_reg_1210 );
    sensitive << ( tmp_48_reg_1216 );

    SC_METHOD(thread_fold_i_cast_fu_711_p2);
    sensitive << ( tmp_42_fu_679_p2 );
    sensitive << ( tmp_43_fu_685_p4 );

    SC_METHOD(thread_grp_fu_1005_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fu_1005_p00 );

    SC_METHOD(thread_grp_fu_1005_p00);
    sensitive << ( tmp_13_reg_1113 );

    SC_METHOD(thread_grp_fu_1012_p0);
    sensitive << ( zj_cast_reg_1078 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_385_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_phi_mux_zj_phi_fu_332_p4 );
    sensitive << ( zj_reg_328 );

    SC_METHOD(thread_grp_fu_385_p2);
    sensitive << ( grp_fu_385_p0 );

    SC_METHOD(thread_grp_fu_982_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( tmp_3_cast_fu_427_p1 );

    SC_METHOD(thread_grp_fu_989_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( tmp_3_cast_fu_427_p1 );

    SC_METHOD(thread_grp_fu_989_p2);
    sensitive << ( a_coeffs_load_reg_1028 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( tmp_6_fu_431_p1 );

    SC_METHOD(thread_grp_fu_996_p0);
    sensitive << ( zj_cast9_reg_1073 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_i_4_fu_421_p2);
    sensitive << ( i_reg_317 );

    SC_METHOD(thread_i_5_fu_513_p2);
    sensitive << ( i_1_reg_340 );

    SC_METHOD(thread_i_6_fu_558_p2);
    sensitive << ( i_2_reg_352 );

    SC_METHOD(thread_i_7_fu_874_p2);
    sensitive << ( i_i_reg_363 );

    SC_METHOD(thread_i_8_fu_936_p2);
    sensitive << ( i_i5_reg_374 );

    SC_METHOD(thread_not_tmp_87_i_fu_837_p2);
    sensitive << ( tmp_59_fu_811_p3 );

    SC_METHOD(thread_r_1_fu_721_p2);
    sensitive << ( tmp_261_i_cast_fu_675_p1 );
    sensitive << ( tmp_262_i_cast_fu_717_p1 );

    SC_METHOD(thread_r_2_fu_772_p2);
    sensitive << ( tmp_263_i_cast_reg_1205 );
    sensitive << ( tmp_264_i_cast_fu_769_p1 );

    SC_METHOD(thread_r_3_fu_799_p2);
    sensitive << ( tmp_265_i_cast_fu_787_p1 );
    sensitive << ( tmp_266_i_cast_fu_795_p1 );

    SC_METHOD(thread_r_coeffs_address0);
    sensitive << ( tmp_235_i_reg_1248 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_r_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_r_coeffs_d0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_237_i_cast_fu_962_p1 );
    sensitive << ( tmp_239_i_cast_fu_977_p1 );

    SC_METHOD(thread_r_coeffs_we0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_r_fu_659_p2);
    sensitive << ( tmp_i_cast_fu_645_p1 );
    sensitive << ( tmp_i_cast_27_fu_649_p1 );

    SC_METHOD(thread_t_fu_805_p2);
    sensitive << ( r_3_fu_799_p2 );

    SC_METHOD(thread_tmp2_fu_527_p2);
    sensitive << ( tmp_28_reg_1177 );
    sensitive << ( tmp_34_fu_523_p1 );

    SC_METHOD(thread_tmp_18_fu_436_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_fu_385_p2 );

    SC_METHOD(thread_tmp_19_fu_448_p3);
    sensitive << ( grp_fu_385_p2 );
    sensitive << ( tmp_18_fu_436_p2 );
    sensitive << ( tmp_27_fu_442_p2 );

    SC_METHOD(thread_tmp_20_fu_476_p2);
    sensitive << ( i_1_reg_340 );

    SC_METHOD(thread_tmp_21_fu_482_p1);
    sensitive << ( tmp_20_fu_476_p2 );

    SC_METHOD(thread_tmp_22_fu_471_p1);
    sensitive << ( i_1_reg_340 );

    SC_METHOD(thread_tmp_235_i_fu_947_p1);
    sensitive << ( i_i5_reg_374 );

    SC_METHOD(thread_tmp_236_i_fu_952_p2);
    sensitive << ( b_coeffs_q1 );
    sensitive << ( b_coeffs_q0 );

    SC_METHOD(thread_tmp_237_i_cast_fu_962_p1);
    sensitive << ( tmp_62_fu_958_p1 );

    SC_METHOD(thread_tmp_238_i_fu_967_p2);
    sensitive << ( reg_392 );
    sensitive << ( b_coeffs_q0 );

    SC_METHOD(thread_tmp_239_i_cast_fu_977_p1);
    sensitive << ( tmp_61_fu_973_p1 );

    SC_METHOD(thread_tmp_23_fu_487_p2);
    sensitive << ( i_1_reg_340 );

    SC_METHOD(thread_tmp_24_fu_493_p1);
    sensitive << ( tmp_23_fu_487_p2 );

    SC_METHOD(thread_tmp_25_fu_498_p2);
    sensitive << ( i_1_reg_340 );

    SC_METHOD(thread_tmp_261_i_cast_fu_675_p1);
    sensitive << ( tmp_57_fu_665_p4 );

    SC_METHOD(thread_tmp_262_i_cast_fu_717_p1);
    sensitive << ( fold_i_cast_fu_711_p2 );

    SC_METHOD(thread_tmp_264_i_cast_fu_769_p1);
    sensitive << ( fold1_i_cast_reg_1210 );

    SC_METHOD(thread_tmp_265_i_cast_fu_787_p1);
    sensitive << ( tmp_58_fu_777_p4 );

    SC_METHOD(thread_tmp_266_i_cast_fu_795_p1);
    sensitive << ( fold2_i_cast_fu_791_p2 );

    SC_METHOD(thread_tmp_267_i_cast_fu_833_p1);
    sensitive << ( tmp_267_i_fu_827_p2 );

    SC_METHOD(thread_tmp_267_i_fu_827_p2);
    sensitive << ( r_3_fu_799_p2 );
    sensitive << ( c_cast_fu_819_p3 );

    SC_METHOD(thread_tmp_268_i_cast_cast_fu_843_p3);
    sensitive << ( not_tmp_87_i_fu_837_p2 );

    SC_METHOD(thread_tmp_269_i_cast_fu_857_p1);
    sensitive << ( tmp_269_i_fu_851_p2 );

    SC_METHOD(thread_tmp_269_i_fu_851_p2);
    sensitive << ( t_fu_805_p2 );
    sensitive << ( tmp_268_i_cast_cast_fu_843_p3 );

    SC_METHOD(thread_tmp_26_fu_504_p1);
    sensitive << ( tmp_25_fu_498_p2 );

    SC_METHOD(thread_tmp_270_i_fu_861_p2);
    sensitive << ( tmp_267_i_cast_fu_833_p1 );
    sensitive << ( tmp_269_i_cast_fu_857_p1 );

    SC_METHOD(thread_tmp_27_fu_442_p2);
    sensitive << ( zj_reg_328 );

    SC_METHOD(thread_tmp_28_fu_509_p1);
    sensitive << ( a_coeffs_q0 );

    SC_METHOD(thread_tmp_29_fu_519_p1);
    sensitive << ( a_coeffs_q1 );

    SC_METHOD(thread_tmp_30_fu_532_p2);
    sensitive << ( tmp2_fu_527_p2 );
    sensitive << ( tmp_29_fu_519_p1 );

    SC_METHOD(thread_tmp_31_fu_538_p3);
    sensitive << ( tmp_30_fu_532_p2 );

    SC_METHOD(thread_tmp_32_fu_546_p2);
    sensitive << ( b_coeffs_q0 );
    sensitive << ( tmp_31_fu_538_p3 );

    SC_METHOD(thread_tmp_33_fu_564_p1);
    sensitive << ( i_2_reg_352 );

    SC_METHOD(thread_tmp_34_fu_523_p1);
    sensitive << ( a_coeffs_q0 );

    SC_METHOD(thread_tmp_35_fu_569_p2);
    sensitive << ( b_coeffs_q1 );

    SC_METHOD(thread_tmp_36_fu_579_p3);
    sensitive << ( tmp_37_fu_575_p1 );

    SC_METHOD(thread_tmp_37_fu_575_p1);
    sensitive << ( b_coeffs_q1 );

    SC_METHOD(thread_tmp_37_i_cast_fu_895_p2);
    sensitive << ( tmp_52_fu_885_p4 );

    SC_METHOD(thread_tmp_38_fu_587_p1);
    sensitive << ( b_coeffs_q0 );

    SC_METHOD(thread_tmp_39_fu_599_p3);
    sensitive << ( tmp_49_fu_595_p1 );

    SC_METHOD(thread_tmp_39_i_fu_921_p3);
    sensitive << ( tmp_55_fu_911_p4 );
    sensitive << ( tmp_54_fu_905_p2 );

    SC_METHOD(thread_tmp_3_cast_fu_427_p1);
    sensitive << ( grp_fu_385_p2 );

    SC_METHOD(thread_tmp_40_fu_611_p3);
    sensitive << ( tmp_50_fu_607_p1 );

    SC_METHOD(thread_tmp_41_fu_591_p1);
    sensitive << ( b_coeffs_q0 );

    SC_METHOD(thread_tmp_42_fu_679_p2);
    sensitive << ( tmp_39_fu_599_p3 );
    sensitive << ( tmp_41_fu_591_p1 );

    SC_METHOD(thread_tmp_43_fu_685_p4);
    sensitive << ( a_assign_fu_623_p2 );

    SC_METHOD(thread_tmp_44_fu_695_p4);
    sensitive << ( a_assign_fu_623_p2 );

    SC_METHOD(thread_tmp_45_fu_705_p2);
    sensitive << ( tmp_40_fu_611_p3 );
    sensitive << ( tmp_51_fu_619_p1 );

    SC_METHOD(thread_tmp_46_fu_737_p2);
    sensitive << ( tmp_45_fu_705_p2 );
    sensitive << ( tmp_44_fu_695_p4 );

    SC_METHOD(thread_tmp_47_fu_743_p4);
    sensitive << ( tmp_56_fu_653_p2 );

    SC_METHOD(thread_tmp_49_fu_595_p1);
    sensitive << ( b_coeffs_q1 );

    SC_METHOD(thread_tmp_50_fu_607_p1);
    sensitive << ( b_coeffs_q1 );

    SC_METHOD(thread_tmp_51_fu_619_p1);
    sensitive << ( b_coeffs_q0 );

    SC_METHOD(thread_tmp_52_fu_885_p4);
    sensitive << ( b_coeffs_q1 );

    SC_METHOD(thread_tmp_53_fu_635_p4);
    sensitive << ( a_assign_fu_623_p2 );

    SC_METHOD(thread_tmp_54_fu_905_p2);
    sensitive << ( tmp_60_fu_901_p1 );
    sensitive << ( tmp_37_i_cast_fu_895_p2 );

    SC_METHOD(thread_tmp_55_fu_911_p4);
    sensitive << ( b_coeffs_q1 );

    SC_METHOD(thread_tmp_56_fu_653_p2);
    sensitive << ( tmp_53_fu_635_p4 );
    sensitive << ( a_assign_cast_fu_629_p2 );

    SC_METHOD(thread_tmp_57_fu_665_p4);
    sensitive << ( r_fu_659_p2 );

    SC_METHOD(thread_tmp_58_fu_777_p4);
    sensitive << ( r_2_fu_772_p2 );

    SC_METHOD(thread_tmp_59_fu_811_p3);
    sensitive << ( t_fu_805_p2 );

    SC_METHOD(thread_tmp_60_fu_901_p1);
    sensitive << ( b_coeffs_q1 );

    SC_METHOD(thread_tmp_61_fu_973_p1);
    sensitive << ( tmp_238_i_fu_967_p2 );

    SC_METHOD(thread_tmp_62_fu_958_p1);
    sensitive << ( tmp_236_i_fu_952_p2 );

    SC_METHOD(thread_tmp_6_fu_431_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_6_fu_431_p10 );

    SC_METHOD(thread_tmp_6_fu_431_p10);
    sensitive << ( zj_reg_328 );

    SC_METHOD(thread_tmp_7_fu_416_p1);
    sensitive << ( i_reg_317 );

    SC_METHOD(thread_tmp_9_fu_459_p2);
    sensitive << ( tmp1_reg_1101 );
    sensitive << ( tmp_1_reg_298 );

    SC_METHOD(thread_tmp_fu_396_p2);
    sensitive << ( a_coeffs_q0 );
    sensitive << ( a_coeffs_load_reg_1028 );

    SC_METHOD(thread_tmp_i3_fu_880_p1);
    sensitive << ( i_i_reg_363 );

    SC_METHOD(thread_tmp_i6_fu_930_p2);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( i_i5_reg_374 );

    SC_METHOD(thread_tmp_i7_fu_942_p1);
    sensitive << ( i_8_fu_936_p2 );

    SC_METHOD(thread_tmp_i_cast_27_fu_649_p1);
    sensitive << ( a_assign_cast_fu_629_p2 );

    SC_METHOD(thread_tmp_i_cast_fu_645_p1);
    sensitive << ( tmp_53_fu_635_p4 );

    SC_METHOD(thread_zj_cast9_fu_402_p1);
    sensitive << ( zj_reg_328 );

    SC_METHOD(thread_zj_cast_fu_406_p1);
    sensitive << ( zj_reg_328 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_410_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond1_fu_465_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( exitcond_fu_552_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( exitcond_i_fu_868_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_i6_fu_930_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "poly_lift_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, r_coeffs_address0, "(port)r_coeffs_address0");
    sc_trace(mVcdFile, r_coeffs_ce0, "(port)r_coeffs_ce0");
    sc_trace(mVcdFile, r_coeffs_we0, "(port)r_coeffs_we0");
    sc_trace(mVcdFile, r_coeffs_d0, "(port)r_coeffs_d0");
    sc_trace(mVcdFile, a_coeffs_address0, "(port)a_coeffs_address0");
    sc_trace(mVcdFile, a_coeffs_ce0, "(port)a_coeffs_ce0");
    sc_trace(mVcdFile, a_coeffs_q0, "(port)a_coeffs_q0");
    sc_trace(mVcdFile, a_coeffs_address1, "(port)a_coeffs_address1");
    sc_trace(mVcdFile, a_coeffs_ce1, "(port)a_coeffs_ce1");
    sc_trace(mVcdFile, a_coeffs_q1, "(port)a_coeffs_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, b_coeffs_q1, "b_coeffs_q1");
    sc_trace(mVcdFile, reg_392, "reg_392");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, a_coeffs_load_reg_1028, "a_coeffs_load_reg_1028");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, a_coeffs_load_1_reg_1035, "a_coeffs_load_1_reg_1035");
    sc_trace(mVcdFile, b_coeffs_addr_1_reg_1046, "b_coeffs_addr_1_reg_1046");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_fu_396_p2, "tmp_fu_396_p2");
    sc_trace(mVcdFile, b_coeffs_addr_reg_1061, "b_coeffs_addr_reg_1061");
    sc_trace(mVcdFile, b_coeffs_addr_2_reg_1067, "b_coeffs_addr_2_reg_1067");
    sc_trace(mVcdFile, zj_cast9_fu_402_p1, "zj_cast9_fu_402_p1");
    sc_trace(mVcdFile, zj_cast9_reg_1073, "zj_cast9_reg_1073");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zj_cast_fu_406_p1, "zj_cast_fu_406_p1");
    sc_trace(mVcdFile, zj_cast_reg_1078, "zj_cast_reg_1078");
    sc_trace(mVcdFile, exitcond2_fu_410_p2, "exitcond2_fu_410_p2");
    sc_trace(mVcdFile, i_4_fu_421_p2, "i_4_fu_421_p2");
    sc_trace(mVcdFile, i_4_reg_1091, "i_4_reg_1091");
    sc_trace(mVcdFile, grp_fu_982_p3, "grp_fu_982_p3");
    sc_trace(mVcdFile, tmp_5_reg_1096, "tmp_5_reg_1096");
    sc_trace(mVcdFile, grp_fu_989_p3, "grp_fu_989_p3");
    sc_trace(mVcdFile, tmp1_reg_1101, "tmp1_reg_1101");
    sc_trace(mVcdFile, a_coeffs_load_3_reg_1106, "a_coeffs_load_3_reg_1106");
    sc_trace(mVcdFile, grp_fu_385_p2, "grp_fu_385_p2");
    sc_trace(mVcdFile, tmp_13_reg_1113, "tmp_13_reg_1113");
    sc_trace(mVcdFile, b_coeffs_q0, "b_coeffs_q0");
    sc_trace(mVcdFile, b_coeffs_load_1_reg_1118, "b_coeffs_load_1_reg_1118");
    sc_trace(mVcdFile, tmp_19_fu_448_p3, "tmp_19_fu_448_p3");
    sc_trace(mVcdFile, tmp_19_reg_1123, "tmp_19_reg_1123");
    sc_trace(mVcdFile, grp_fu_996_p4, "grp_fu_996_p4");
    sc_trace(mVcdFile, tmp_12_reg_1128, "tmp_12_reg_1128");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_1005_p3, "grp_fu_1005_p3");
    sc_trace(mVcdFile, tmp_15_reg_1133, "tmp_15_reg_1133");
    sc_trace(mVcdFile, grp_fu_1012_p3, "grp_fu_1012_p3");
    sc_trace(mVcdFile, tmp_17_reg_1138, "tmp_17_reg_1138");
    sc_trace(mVcdFile, tmp_22_fu_471_p1, "tmp_22_fu_471_p1");
    sc_trace(mVcdFile, tmp_22_reg_1147, "tmp_22_reg_1147");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, exitcond1_fu_465_p2, "exitcond1_fu_465_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_28_fu_509_p1, "tmp_28_fu_509_p1");
    sc_trace(mVcdFile, tmp_28_reg_1177, "tmp_28_reg_1177");
    sc_trace(mVcdFile, i_5_fu_513_p2, "i_5_fu_513_p2");
    sc_trace(mVcdFile, i_5_reg_1182, "i_5_reg_1182");
    sc_trace(mVcdFile, tmp_32_fu_546_p2, "tmp_32_fu_546_p2");
    sc_trace(mVcdFile, tmp_32_reg_1187, "tmp_32_reg_1187");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, i_6_fu_558_p2, "i_6_fu_558_p2");
    sc_trace(mVcdFile, i_6_reg_1195, "i_6_reg_1195");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, b_coeffs_addr_6_reg_1200, "b_coeffs_addr_6_reg_1200");
    sc_trace(mVcdFile, exitcond_fu_552_p2, "exitcond_fu_552_p2");
    sc_trace(mVcdFile, tmp_263_i_cast_reg_1205, "tmp_263_i_cast_reg_1205");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, fold1_i_cast_fu_753_p2, "fold1_i_cast_fu_753_p2");
    sc_trace(mVcdFile, fold1_i_cast_reg_1210, "fold1_i_cast_reg_1210");
    sc_trace(mVcdFile, tmp_48_reg_1216, "tmp_48_reg_1216");
    sc_trace(mVcdFile, i_7_fu_874_p2, "i_7_fu_874_p2");
    sc_trace(mVcdFile, i_7_reg_1224, "i_7_reg_1224");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, b_coeffs_addr_7_reg_1229, "b_coeffs_addr_7_reg_1229");
    sc_trace(mVcdFile, exitcond_i_fu_868_p2, "exitcond_i_fu_868_p2");
    sc_trace(mVcdFile, i_8_fu_936_p2, "i_8_fu_936_p2");
    sc_trace(mVcdFile, i_8_reg_1238, "i_8_reg_1238");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_i6_fu_930_p2, "tmp_i6_fu_930_p2");
    sc_trace(mVcdFile, tmp_235_i_fu_947_p1, "tmp_235_i_fu_947_p1");
    sc_trace(mVcdFile, tmp_235_i_reg_1248, "tmp_235_i_reg_1248");
    sc_trace(mVcdFile, b_coeffs_address0, "b_coeffs_address0");
    sc_trace(mVcdFile, b_coeffs_ce0, "b_coeffs_ce0");
    sc_trace(mVcdFile, b_coeffs_we0, "b_coeffs_we0");
    sc_trace(mVcdFile, b_coeffs_d0, "b_coeffs_d0");
    sc_trace(mVcdFile, b_coeffs_address1, "b_coeffs_address1");
    sc_trace(mVcdFile, b_coeffs_ce1, "b_coeffs_ce1");
    sc_trace(mVcdFile, b_coeffs_we1, "b_coeffs_we1");
    sc_trace(mVcdFile, b_coeffs_d1, "b_coeffs_d1");
    sc_trace(mVcdFile, tmp_s_reg_288, "tmp_s_reg_288");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_1_reg_298, "tmp_1_reg_298");
    sc_trace(mVcdFile, tmp_2_reg_308, "tmp_2_reg_308");
    sc_trace(mVcdFile, i_reg_317, "i_reg_317");
    sc_trace(mVcdFile, ap_phi_mux_zj_phi_fu_332_p4, "ap_phi_mux_zj_phi_fu_332_p4");
    sc_trace(mVcdFile, zj_reg_328, "zj_reg_328");
    sc_trace(mVcdFile, i_1_reg_340, "i_1_reg_340");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, i_2_reg_352, "i_2_reg_352");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, i_i_reg_363, "i_i_reg_363");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, i_i5_reg_374, "i_i5_reg_374");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, tmp_7_fu_416_p1, "tmp_7_fu_416_p1");
    sc_trace(mVcdFile, tmp_21_fu_482_p1, "tmp_21_fu_482_p1");
    sc_trace(mVcdFile, tmp_24_fu_493_p1, "tmp_24_fu_493_p1");
    sc_trace(mVcdFile, tmp_26_fu_504_p1, "tmp_26_fu_504_p1");
    sc_trace(mVcdFile, tmp_33_fu_564_p1, "tmp_33_fu_564_p1");
    sc_trace(mVcdFile, tmp_i3_fu_880_p1, "tmp_i3_fu_880_p1");
    sc_trace(mVcdFile, tmp_i7_fu_942_p1, "tmp_i7_fu_942_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, tmp_9_fu_459_p2, "tmp_9_fu_459_p2");
    sc_trace(mVcdFile, tmp_270_i_fu_861_p2, "tmp_270_i_fu_861_p2");
    sc_trace(mVcdFile, tmp_39_i_fu_921_p3, "tmp_39_i_fu_921_p3");
    sc_trace(mVcdFile, tmp_237_i_cast_fu_962_p1, "tmp_237_i_cast_fu_962_p1");
    sc_trace(mVcdFile, tmp_239_i_cast_fu_977_p1, "tmp_239_i_cast_fu_977_p1");
    sc_trace(mVcdFile, grp_fu_385_p0, "grp_fu_385_p0");
    sc_trace(mVcdFile, tmp_6_fu_431_p1, "tmp_6_fu_431_p1");
    sc_trace(mVcdFile, tmp_18_fu_436_p2, "tmp_18_fu_436_p2");
    sc_trace(mVcdFile, tmp_27_fu_442_p2, "tmp_27_fu_442_p2");
    sc_trace(mVcdFile, tmp_20_fu_476_p2, "tmp_20_fu_476_p2");
    sc_trace(mVcdFile, tmp_23_fu_487_p2, "tmp_23_fu_487_p2");
    sc_trace(mVcdFile, tmp_25_fu_498_p2, "tmp_25_fu_498_p2");
    sc_trace(mVcdFile, tmp_34_fu_523_p1, "tmp_34_fu_523_p1");
    sc_trace(mVcdFile, tmp2_fu_527_p2, "tmp2_fu_527_p2");
    sc_trace(mVcdFile, tmp_29_fu_519_p1, "tmp_29_fu_519_p1");
    sc_trace(mVcdFile, tmp_30_fu_532_p2, "tmp_30_fu_532_p2");
    sc_trace(mVcdFile, tmp_31_fu_538_p3, "tmp_31_fu_538_p3");
    sc_trace(mVcdFile, tmp_37_fu_575_p1, "tmp_37_fu_575_p1");
    sc_trace(mVcdFile, tmp_49_fu_595_p1, "tmp_49_fu_595_p1");
    sc_trace(mVcdFile, tmp_50_fu_607_p1, "tmp_50_fu_607_p1");
    sc_trace(mVcdFile, tmp_35_fu_569_p2, "tmp_35_fu_569_p2");
    sc_trace(mVcdFile, tmp_36_fu_579_p3, "tmp_36_fu_579_p3");
    sc_trace(mVcdFile, tmp_38_fu_587_p1, "tmp_38_fu_587_p1");
    sc_trace(mVcdFile, a_assign_fu_623_p2, "a_assign_fu_623_p2");
    sc_trace(mVcdFile, tmp_53_fu_635_p4, "tmp_53_fu_635_p4");
    sc_trace(mVcdFile, a_assign_cast_fu_629_p2, "a_assign_cast_fu_629_p2");
    sc_trace(mVcdFile, tmp_i_cast_fu_645_p1, "tmp_i_cast_fu_645_p1");
    sc_trace(mVcdFile, tmp_i_cast_27_fu_649_p1, "tmp_i_cast_27_fu_649_p1");
    sc_trace(mVcdFile, r_fu_659_p2, "r_fu_659_p2");
    sc_trace(mVcdFile, tmp_57_fu_665_p4, "tmp_57_fu_665_p4");
    sc_trace(mVcdFile, tmp_39_fu_599_p3, "tmp_39_fu_599_p3");
    sc_trace(mVcdFile, tmp_41_fu_591_p1, "tmp_41_fu_591_p1");
    sc_trace(mVcdFile, tmp_40_fu_611_p3, "tmp_40_fu_611_p3");
    sc_trace(mVcdFile, tmp_51_fu_619_p1, "tmp_51_fu_619_p1");
    sc_trace(mVcdFile, tmp_42_fu_679_p2, "tmp_42_fu_679_p2");
    sc_trace(mVcdFile, tmp_43_fu_685_p4, "tmp_43_fu_685_p4");
    sc_trace(mVcdFile, fold_i_cast_fu_711_p2, "fold_i_cast_fu_711_p2");
    sc_trace(mVcdFile, tmp_261_i_cast_fu_675_p1, "tmp_261_i_cast_fu_675_p1");
    sc_trace(mVcdFile, tmp_262_i_cast_fu_717_p1, "tmp_262_i_cast_fu_717_p1");
    sc_trace(mVcdFile, r_1_fu_721_p2, "r_1_fu_721_p2");
    sc_trace(mVcdFile, tmp_45_fu_705_p2, "tmp_45_fu_705_p2");
    sc_trace(mVcdFile, tmp_44_fu_695_p4, "tmp_44_fu_695_p4");
    sc_trace(mVcdFile, tmp_56_fu_653_p2, "tmp_56_fu_653_p2");
    sc_trace(mVcdFile, tmp_46_fu_737_p2, "tmp_46_fu_737_p2");
    sc_trace(mVcdFile, tmp_47_fu_743_p4, "tmp_47_fu_743_p4");
    sc_trace(mVcdFile, tmp_264_i_cast_fu_769_p1, "tmp_264_i_cast_fu_769_p1");
    sc_trace(mVcdFile, r_2_fu_772_p2, "r_2_fu_772_p2");
    sc_trace(mVcdFile, tmp_58_fu_777_p4, "tmp_58_fu_777_p4");
    sc_trace(mVcdFile, fold2_i_cast_fu_791_p2, "fold2_i_cast_fu_791_p2");
    sc_trace(mVcdFile, tmp_265_i_cast_fu_787_p1, "tmp_265_i_cast_fu_787_p1");
    sc_trace(mVcdFile, tmp_266_i_cast_fu_795_p1, "tmp_266_i_cast_fu_795_p1");
    sc_trace(mVcdFile, r_3_fu_799_p2, "r_3_fu_799_p2");
    sc_trace(mVcdFile, t_fu_805_p2, "t_fu_805_p2");
    sc_trace(mVcdFile, tmp_59_fu_811_p3, "tmp_59_fu_811_p3");
    sc_trace(mVcdFile, c_cast_fu_819_p3, "c_cast_fu_819_p3");
    sc_trace(mVcdFile, tmp_267_i_fu_827_p2, "tmp_267_i_fu_827_p2");
    sc_trace(mVcdFile, not_tmp_87_i_fu_837_p2, "not_tmp_87_i_fu_837_p2");
    sc_trace(mVcdFile, tmp_268_i_cast_cast_fu_843_p3, "tmp_268_i_cast_cast_fu_843_p3");
    sc_trace(mVcdFile, tmp_269_i_fu_851_p2, "tmp_269_i_fu_851_p2");
    sc_trace(mVcdFile, tmp_267_i_cast_fu_833_p1, "tmp_267_i_cast_fu_833_p1");
    sc_trace(mVcdFile, tmp_269_i_cast_fu_857_p1, "tmp_269_i_cast_fu_857_p1");
    sc_trace(mVcdFile, tmp_52_fu_885_p4, "tmp_52_fu_885_p4");
    sc_trace(mVcdFile, tmp_60_fu_901_p1, "tmp_60_fu_901_p1");
    sc_trace(mVcdFile, tmp_37_i_cast_fu_895_p2, "tmp_37_i_cast_fu_895_p2");
    sc_trace(mVcdFile, tmp_55_fu_911_p4, "tmp_55_fu_911_p4");
    sc_trace(mVcdFile, tmp_54_fu_905_p2, "tmp_54_fu_905_p2");
    sc_trace(mVcdFile, tmp_236_i_fu_952_p2, "tmp_236_i_fu_952_p2");
    sc_trace(mVcdFile, tmp_62_fu_958_p1, "tmp_62_fu_958_p1");
    sc_trace(mVcdFile, tmp_238_i_fu_967_p2, "tmp_238_i_fu_967_p2");
    sc_trace(mVcdFile, tmp_61_fu_973_p1, "tmp_61_fu_973_p1");
    sc_trace(mVcdFile, grp_fu_982_p1, "grp_fu_982_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_427_p1, "tmp_3_cast_fu_427_p1");
    sc_trace(mVcdFile, grp_fu_989_p1, "grp_fu_989_p1");
    sc_trace(mVcdFile, grp_fu_989_p2, "grp_fu_989_p2");
    sc_trace(mVcdFile, grp_fu_996_p0, "grp_fu_996_p0");
    sc_trace(mVcdFile, grp_fu_1005_p0, "grp_fu_1005_p0");
    sc_trace(mVcdFile, grp_fu_1012_p0, "grp_fu_1012_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_1005_p00, "grp_fu_1005_p00");
    sc_trace(mVcdFile, tmp_6_fu_431_p10, "tmp_6_fu_431_p10");
#endif

    }
}

poly_lift::~poly_lift() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete b_coeffs_U;
    delete crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U23;
    delete crypto_kem_dec_mac_muladd_16s_2ns_16ns_16_1_1_U24;
    delete crypto_kem_dec_ama_addmuladd_2ns_3ns_16s_16ns_16_1_1_U25;
    delete crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U26;
    delete crypto_kem_dec_mac_muladd_2ns_16s_16ns_16_1_1_U27;
}

void poly_lift::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv3_2;
}

void poly_lift::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i_1_reg_340 = i_5_reg_1182.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_1_reg_340 = ap_const_lv10_3;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_465_p2.read()))) {
        i_2_reg_352 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_2_reg_352 = i_6_reg_1195.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        i_i5_reg_374 = i_8_reg_1238.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        i_i5_reg_374 = ap_const_lv10_2BC;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_552_p2.read()))) {
        i_i_reg_363 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        i_i_reg_363 = i_7_reg_1224.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i_reg_317 = i_4_reg_1091.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_317 = ap_const_lv10_3;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_1_reg_298 = tmp_17_reg_1138.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_1_reg_298 = a_coeffs_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_2_reg_308 = tmp_15_reg_1133.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_2_reg_308 = a_coeffs_load_1_reg_1035.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_s_reg_288 = tmp_12_reg_1128.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_s_reg_288 = tmp_fu_396_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        zj_reg_328 = tmp_19_reg_1123.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        zj_reg_328 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        a_coeffs_load_1_reg_1035 = a_coeffs_q1.read();
        a_coeffs_load_reg_1028 = a_coeffs_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_coeffs_load_3_reg_1106 = a_coeffs_q1.read();
        b_coeffs_load_1_reg_1118 = b_coeffs_q0.read();
        tmp_13_reg_1113 = grp_fu_385_p2.read();
        tmp_19_reg_1123 = tmp_19_fu_448_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_552_p2.read()))) {
        b_coeffs_addr_6_reg_1200 =  (sc_lv<10>) (tmp_33_fu_564_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_868_p2.read()))) {
        b_coeffs_addr_7_reg_1229 =  (sc_lv<10>) (tmp_i3_fu_880_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        fold1_i_cast_reg_1210 = fold1_i_cast_fu_753_p2.read();
        tmp_263_i_cast_reg_1205 = r_1_fu_721_p2.read().range(5, 2);
        tmp_48_reg_1216 = r_1_fu_721_p2.read().range(3, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_0))) {
        i_4_reg_1091 = i_4_fu_421_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_5_reg_1182 = i_5_fu_513_p2.read();
        tmp_28_reg_1177 = tmp_28_fu_509_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        i_6_reg_1195 = i_6_fu_558_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        i_7_reg_1224 = i_7_fu_874_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i6_fu_930_p2.read()))) {
        i_8_reg_1238 = i_8_fu_936_p2.read();
        tmp_235_i_reg_1248 = tmp_235_i_fu_947_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        reg_392 = b_coeffs_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_1))) {
        tmp1_reg_1101 = grp_fu_989_p3.read();
        tmp_5_reg_1096 = grp_fu_982_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_12_reg_1128 = grp_fu_996_p4.read();
        tmp_15_reg_1133 = grp_fu_1005_p3.read();
        tmp_17_reg_1138 = grp_fu_1012_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_465_p2.read()))) {
        tmp_22_reg_1147 = tmp_22_fu_471_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        tmp_32_reg_1187 = tmp_32_fu_546_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        zj_cast9_reg_1073 = zj_cast9_fu_402_p1.read();
        zj_cast_reg_1078 = zj_cast_fu_406_p1.read();
    }
}

void poly_lift::thread_a_assign_cast_fu_629_p2() {
    a_assign_cast_fu_629_p2 = (!tmp_36_fu_579_p3.read().is_01() || !tmp_38_fu_587_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_36_fu_579_p3.read()) + sc_biguint<8>(tmp_38_fu_587_p1.read()));
}

void poly_lift::thread_a_assign_fu_623_p2() {
    a_assign_fu_623_p2 = (!b_coeffs_q0.read().is_01() || !tmp_35_fu_569_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(b_coeffs_q0.read()) + sc_biguint<16>(tmp_35_fu_569_p2.read()));
}

void poly_lift::thread_a_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (tmp_26_fu_504_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (tmp_22_fu_471_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (ap_const_lv64_0);
    } else {
        a_coeffs_address0 = "XXXXXXXXXX";
    }
}

void poly_lift::thread_a_coeffs_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        a_coeffs_address1 =  (sc_lv<10>) (tmp_24_fu_493_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        a_coeffs_address1 =  (sc_lv<10>) (tmp_7_fu_416_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        a_coeffs_address1 =  (sc_lv<10>) (ap_const_lv64_1);
    } else {
        a_coeffs_address1 = "XXXXXXXXXX";
    }
}

void poly_lift::thread_a_coeffs_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        a_coeffs_ce0 = ap_const_logic_1;
    } else {
        a_coeffs_ce0 = ap_const_logic_0;
    }
}

void poly_lift::thread_a_coeffs_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        a_coeffs_ce1 = ap_const_logic_1;
    } else {
        a_coeffs_ce1 = ap_const_logic_0;
    }
}

void poly_lift::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void poly_lift::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void poly_lift::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void poly_lift::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void poly_lift::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void poly_lift::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void poly_lift::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void poly_lift::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void poly_lift::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void poly_lift::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void poly_lift::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void poly_lift::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void poly_lift::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void poly_lift::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void poly_lift::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void poly_lift::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void poly_lift::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void poly_lift::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void poly_lift::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void poly_lift::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void poly_lift::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void poly_lift::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void poly_lift::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void poly_lift::thread_ap_phi_mux_zj_phi_fu_332_p4() {
    ap_phi_mux_zj_phi_fu_332_p4 = zj_reg_328.read();
}

void poly_lift::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void poly_lift::thread_b_coeffs_addr_1_reg_1046() {
    b_coeffs_addr_1_reg_1046 =  (sc_lv<10>) (ap_const_lv64_1);
}

void poly_lift::thread_b_coeffs_addr_2_reg_1067() {
    b_coeffs_addr_2_reg_1067 =  (sc_lv<10>) (ap_const_lv64_2);
}

void poly_lift::thread_b_coeffs_addr_reg_1061() {
    b_coeffs_addr_reg_1061 =  (sc_lv<10>) (ap_const_lv64_0);
}

void poly_lift::thread_b_coeffs_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i6_fu_930_p2.read()))) {
        b_coeffs_address0 = b_coeffs_addr_reg_1061.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i6_fu_930_p2.read()))) {
        b_coeffs_address0 =  (sc_lv<10>) (tmp_i7_fu_942_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        b_coeffs_address0 = b_coeffs_addr_7_reg_1229.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        b_coeffs_address0 = b_coeffs_addr_6_reg_1200.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        b_coeffs_address0 =  (sc_lv<10>) (tmp_33_fu_564_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        b_coeffs_address0 =  (sc_lv<10>) (tmp_21_fu_482_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        b_coeffs_address0 =  (sc_lv<10>) (ap_const_lv64_2);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        b_coeffs_address0 = b_coeffs_addr_1_reg_1046.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        b_coeffs_address0 =  (sc_lv<10>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        b_coeffs_address0 =  (sc_lv<10>) (ap_const_lv64_1);
    } else {
        b_coeffs_address0 = "XXXXXXXXXX";
    }
}

void poly_lift::thread_b_coeffs_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        b_coeffs_address1 =  (sc_lv<10>) (tmp_235_i_fu_947_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_868_p2.read()))) {
        b_coeffs_address1 =  (sc_lv<10>) (tmp_i3_fu_880_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_868_p2.read())))) {
        b_coeffs_address1 =  (sc_lv<10>) (ap_const_lv64_2BC);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        b_coeffs_address1 =  (sc_lv<10>) (tmp_22_reg_1147.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        b_coeffs_address1 = b_coeffs_addr_2_reg_1067.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                 esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                 esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_1)) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        b_coeffs_address1 =  (sc_lv<10>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        b_coeffs_address1 =  (sc_lv<10>) (ap_const_lv64_2);
    } else {
        b_coeffs_address1 = "XXXXXXXXXX";
    }
}

void poly_lift::thread_b_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i6_fu_930_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i6_fu_930_p2.read())))) {
        b_coeffs_ce0 = ap_const_logic_1;
    } else {
        b_coeffs_ce0 = ap_const_logic_0;
    }
}

void poly_lift::thread_b_coeffs_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_868_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_868_p2.read())))) {
        b_coeffs_ce1 = ap_const_logic_1;
    } else {
        b_coeffs_ce1 = ap_const_logic_0;
    }
}

void poly_lift::thread_b_coeffs_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        b_coeffs_d0 = tmp_39_i_fu_921_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        b_coeffs_d0 = tmp_270_i_fu_861_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        b_coeffs_d0 = tmp_5_reg_1096.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        b_coeffs_d0 = grp_fu_1005_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        b_coeffs_d0 = tmp_fu_396_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        b_coeffs_d0 = a_coeffs_q1.read();
    } else {
        b_coeffs_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void poly_lift::thread_b_coeffs_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        b_coeffs_d1 = tmp_32_reg_1187.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        b_coeffs_d1 = tmp_9_fu_459_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        b_coeffs_d1 = tmp_17_reg_1138.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        b_coeffs_d1 = grp_fu_996_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_1))) {
        b_coeffs_d1 = tmp_s_reg_288.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        b_coeffs_d1 = a_coeffs_q0.read();
    } else {
        b_coeffs_d1 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void poly_lift::thread_b_coeffs_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        b_coeffs_we0 = ap_const_logic_1;
    } else {
        b_coeffs_we0 = ap_const_logic_0;
    }
}

void poly_lift::thread_b_coeffs_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        b_coeffs_we1 = ap_const_logic_1;
    } else {
        b_coeffs_we1 = ap_const_logic_0;
    }
}

void poly_lift::thread_c_cast_fu_819_p3() {
    c_cast_fu_819_p3 = (!tmp_59_fu_811_p3.read()[0].is_01())? sc_lv<3>(): ((tmp_59_fu_811_p3.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_0);
}

void poly_lift::thread_exitcond1_fu_465_p2() {
    exitcond1_fu_465_p2 = (!i_1_reg_340.read().is_01() || !ap_const_lv10_2BD.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_340.read() == ap_const_lv10_2BD);
}

void poly_lift::thread_exitcond2_fu_410_p2() {
    exitcond2_fu_410_p2 = (!i_reg_317.read().is_01() || !ap_const_lv10_2BD.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_317.read() == ap_const_lv10_2BD);
}

void poly_lift::thread_exitcond_fu_552_p2() {
    exitcond_fu_552_p2 = (!i_2_reg_352.read().is_01() || !ap_const_lv10_2BD.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_352.read() == ap_const_lv10_2BD);
}

void poly_lift::thread_exitcond_i_fu_868_p2() {
    exitcond_i_fu_868_p2 = (!i_i_reg_363.read().is_01() || !ap_const_lv10_2BD.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_363.read() == ap_const_lv10_2BD);
}

void poly_lift::thread_fold1_i_cast_fu_753_p2() {
    fold1_i_cast_fu_753_p2 = (!tmp_46_fu_737_p2.read().is_01() || !tmp_47_fu_743_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_46_fu_737_p2.read()) + sc_biguint<2>(tmp_47_fu_743_p4.read()));
}

void poly_lift::thread_fold2_i_cast_fu_791_p2() {
    fold2_i_cast_fu_791_p2 = (!tmp_48_reg_1216.read().is_01() || !fold1_i_cast_reg_1210.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_48_reg_1216.read()) + sc_biguint<2>(fold1_i_cast_reg_1210.read()));
}

void poly_lift::thread_fold_i_cast_fu_711_p2() {
    fold_i_cast_fu_711_p2 = (!tmp_42_fu_679_p2.read().is_01() || !tmp_43_fu_685_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_42_fu_679_p2.read()) + sc_biguint<4>(tmp_43_fu_685_p4.read()));
}

void poly_lift::thread_grp_fu_1005_p0() {
    grp_fu_1005_p0 =  (sc_lv<2>) (grp_fu_1005_p00.read());
}

void poly_lift::thread_grp_fu_1005_p00() {
    grp_fu_1005_p00 = esl_zext<16,2>(tmp_13_reg_1113.read());
}

void poly_lift::thread_grp_fu_1012_p0() {
    grp_fu_1012_p0 =  (sc_lv<2>) (zj_cast_reg_1078.read());
}

void poly_lift::thread_grp_fu_385_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_385_p0 = zj_reg_328.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_385_p0 = ap_phi_mux_zj_phi_fu_332_p4.read();
    } else {
        grp_fu_385_p0 =  (sc_lv<2>) ("XX");
    }
}

void poly_lift::thread_grp_fu_385_p2() {
    grp_fu_385_p2 = (!grp_fu_385_p0.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(grp_fu_385_p0.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void poly_lift::thread_grp_fu_982_p1() {
    grp_fu_982_p1 =  (sc_lv<2>) (tmp_3_cast_fu_427_p1.read());
}

void poly_lift::thread_grp_fu_989_p1() {
    grp_fu_989_p1 =  (sc_lv<2>) (tmp_3_cast_fu_427_p1.read());
}

void poly_lift::thread_grp_fu_989_p2() {
    grp_fu_989_p2 = (!a_coeffs_load_reg_1028.read().is_01() || !tmp_6_fu_431_p1.read().is_01())? sc_lv<16>(): sc_bigint<16>(a_coeffs_load_reg_1028.read()) * sc_biguint<2>(tmp_6_fu_431_p1.read());
}

void poly_lift::thread_grp_fu_996_p0() {
    grp_fu_996_p0 =  (sc_lv<2>) (zj_cast9_reg_1073.read());
}

void poly_lift::thread_i_4_fu_421_p2() {
    i_4_fu_421_p2 = (!i_reg_317.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_reg_317.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void poly_lift::thread_i_5_fu_513_p2() {
    i_5_fu_513_p2 = (!ap_const_lv10_1.is_01() || !i_1_reg_340.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(i_1_reg_340.read()));
}

void poly_lift::thread_i_6_fu_558_p2() {
    i_6_fu_558_p2 = (!i_2_reg_352.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_2_reg_352.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void poly_lift::thread_i_7_fu_874_p2() {
    i_7_fu_874_p2 = (!i_i_reg_363.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_i_reg_363.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void poly_lift::thread_i_8_fu_936_p2() {
    i_8_fu_936_p2 = (!ap_const_lv10_3FF.is_01() || !i_i5_reg_374.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3FF) + sc_biguint<10>(i_i5_reg_374.read()));
}

void poly_lift::thread_not_tmp_87_i_fu_837_p2() {
    not_tmp_87_i_fu_837_p2 = (tmp_59_fu_811_p3.read() ^ ap_const_lv1_1);
}

void poly_lift::thread_r_1_fu_721_p2() {
    r_1_fu_721_p2 = (!tmp_261_i_cast_fu_675_p1.read().is_01() || !tmp_262_i_cast_fu_717_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_261_i_cast_fu_675_p1.read()) + sc_biguint<6>(tmp_262_i_cast_fu_717_p1.read()));
}

void poly_lift::thread_r_2_fu_772_p2() {
    r_2_fu_772_p2 = (!tmp_263_i_cast_reg_1205.read().is_01() || !tmp_264_i_cast_fu_769_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_263_i_cast_reg_1205.read()) + sc_biguint<4>(tmp_264_i_cast_fu_769_p1.read()));
}

void poly_lift::thread_r_3_fu_799_p2() {
    r_3_fu_799_p2 = (!tmp_265_i_cast_fu_787_p1.read().is_01() || !tmp_266_i_cast_fu_795_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp_265_i_cast_fu_787_p1.read()) + sc_biguint<3>(tmp_266_i_cast_fu_795_p1.read()));
}

void poly_lift::thread_r_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_235_i_reg_1248.read());
    } else {
        r_coeffs_address0 = "XXXXXXXXXX";
    }
}

void poly_lift::thread_r_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        r_coeffs_ce0 = ap_const_logic_1;
    } else {
        r_coeffs_ce0 = ap_const_logic_0;
    }
}

void poly_lift::thread_r_coeffs_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        r_coeffs_d0 = tmp_239_i_cast_fu_977_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        r_coeffs_d0 = tmp_237_i_cast_fu_962_p1.read();
    } else {
        r_coeffs_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void poly_lift::thread_r_coeffs_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        r_coeffs_we0 = ap_const_logic_1;
    } else {
        r_coeffs_we0 = ap_const_logic_0;
    }
}

void poly_lift::thread_r_fu_659_p2() {
    r_fu_659_p2 = (!tmp_i_cast_fu_645_p1.read().is_01() || !tmp_i_cast_27_fu_649_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_i_cast_fu_645_p1.read()) + sc_biguint<9>(tmp_i_cast_27_fu_649_p1.read()));
}

void poly_lift::thread_t_fu_805_p2() {
    t_fu_805_p2 = (!ap_const_lv3_5.is_01() || !r_3_fu_799_p2.read().is_01())? sc_lv<3>(): (sc_bigint<3>(ap_const_lv3_5) + sc_biguint<3>(r_3_fu_799_p2.read()));
}

void poly_lift::thread_tmp2_fu_527_p2() {
    tmp2_fu_527_p2 = (!tmp_28_reg_1177.read().is_01() || !tmp_34_fu_523_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_28_reg_1177.read()) + sc_biguint<15>(tmp_34_fu_523_p1.read()));
}

void poly_lift::thread_tmp_18_fu_436_p2() {
    tmp_18_fu_436_p2 = (!grp_fu_385_p2.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(grp_fu_385_p2.read() != ap_const_lv2_3);
}

void poly_lift::thread_tmp_19_fu_448_p3() {
    tmp_19_fu_448_p3 = (!tmp_18_fu_436_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_18_fu_436_p2.read()[0].to_bool())? grp_fu_385_p2.read(): tmp_27_fu_442_p2.read());
}

void poly_lift::thread_tmp_20_fu_476_p2() {
    tmp_20_fu_476_p2 = (!ap_const_lv10_3FD.is_01() || !i_1_reg_340.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3FD) + sc_biguint<10>(i_1_reg_340.read()));
}

void poly_lift::thread_tmp_21_fu_482_p1() {
    tmp_21_fu_482_p1 = esl_zext<64,10>(tmp_20_fu_476_p2.read());
}

void poly_lift::thread_tmp_22_fu_471_p1() {
    tmp_22_fu_471_p1 = esl_zext<64,10>(i_1_reg_340.read());
}

void poly_lift::thread_tmp_235_i_fu_947_p1() {
    tmp_235_i_fu_947_p1 = esl_zext<64,10>(i_i5_reg_374.read());
}

void poly_lift::thread_tmp_236_i_fu_952_p2() {
    tmp_236_i_fu_952_p2 = (!b_coeffs_q0.read().is_01() || !b_coeffs_q1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(b_coeffs_q0.read()) - sc_biguint<16>(b_coeffs_q1.read()));
}

void poly_lift::thread_tmp_237_i_cast_fu_962_p1() {
    tmp_237_i_cast_fu_962_p1 = esl_zext<16,13>(tmp_62_fu_958_p1.read());
}

void poly_lift::thread_tmp_238_i_fu_967_p2() {
    tmp_238_i_fu_967_p2 = (!reg_392.read().is_01() || !b_coeffs_q0.read().is_01())? sc_lv<16>(): (sc_biguint<16>(reg_392.read()) - sc_biguint<16>(b_coeffs_q0.read()));
}

void poly_lift::thread_tmp_239_i_cast_fu_977_p1() {
    tmp_239_i_cast_fu_977_p1 = esl_zext<16,13>(tmp_61_fu_973_p1.read());
}

void poly_lift::thread_tmp_23_fu_487_p2() {
    tmp_23_fu_487_p2 = (!ap_const_lv10_3FF.is_01() || !i_1_reg_340.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3FF) + sc_biguint<10>(i_1_reg_340.read()));
}

void poly_lift::thread_tmp_24_fu_493_p1() {
    tmp_24_fu_493_p1 = esl_zext<64,10>(tmp_23_fu_487_p2.read());
}

void poly_lift::thread_tmp_25_fu_498_p2() {
    tmp_25_fu_498_p2 = (!ap_const_lv10_3FE.is_01() || !i_1_reg_340.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3FE) + sc_biguint<10>(i_1_reg_340.read()));
}

void poly_lift::thread_tmp_261_i_cast_fu_675_p1() {
    tmp_261_i_cast_fu_675_p1 = esl_zext<6,5>(tmp_57_fu_665_p4.read());
}

void poly_lift::thread_tmp_262_i_cast_fu_717_p1() {
    tmp_262_i_cast_fu_717_p1 = esl_zext<6,4>(fold_i_cast_fu_711_p2.read());
}

void poly_lift::thread_tmp_264_i_cast_fu_769_p1() {
    tmp_264_i_cast_fu_769_p1 = esl_zext<4,2>(fold1_i_cast_reg_1210.read());
}

void poly_lift::thread_tmp_265_i_cast_fu_787_p1() {
    tmp_265_i_cast_fu_787_p1 = esl_zext<3,2>(tmp_58_fu_777_p4.read());
}

void poly_lift::thread_tmp_266_i_cast_fu_795_p1() {
    tmp_266_i_cast_fu_795_p1 = esl_zext<3,2>(fold2_i_cast_fu_791_p2.read());
}

void poly_lift::thread_tmp_267_i_cast_fu_833_p1() {
    tmp_267_i_cast_fu_833_p1 = esl_zext<16,3>(tmp_267_i_fu_827_p2.read());
}

void poly_lift::thread_tmp_267_i_fu_827_p2() {
    tmp_267_i_fu_827_p2 = (r_3_fu_799_p2.read() & c_cast_fu_819_p3.read());
}

void poly_lift::thread_tmp_268_i_cast_cast_fu_843_p3() {
    tmp_268_i_cast_cast_fu_843_p3 = (!not_tmp_87_i_fu_837_p2.read()[0].is_01())? sc_lv<3>(): ((not_tmp_87_i_fu_837_p2.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_0);
}

void poly_lift::thread_tmp_269_i_cast_fu_857_p1() {
    tmp_269_i_cast_fu_857_p1 = esl_sext<16,3>(tmp_269_i_fu_851_p2.read());
}

void poly_lift::thread_tmp_269_i_fu_851_p2() {
    tmp_269_i_fu_851_p2 = (t_fu_805_p2.read() & tmp_268_i_cast_cast_fu_843_p3.read());
}

void poly_lift::thread_tmp_26_fu_504_p1() {
    tmp_26_fu_504_p1 = esl_zext<64,10>(tmp_25_fu_498_p2.read());
}

void poly_lift::thread_tmp_270_i_fu_861_p2() {
    tmp_270_i_fu_861_p2 = (tmp_267_i_cast_fu_833_p1.read() ^ tmp_269_i_cast_fu_857_p1.read());
}

void poly_lift::thread_tmp_27_fu_442_p2() {
    tmp_27_fu_442_p2 = (zj_reg_328.read() ^ ap_const_lv2_2);
}

void poly_lift::thread_tmp_28_fu_509_p1() {
    tmp_28_fu_509_p1 = a_coeffs_q0.read().range(15-1, 0);
}

void poly_lift::thread_tmp_29_fu_519_p1() {
    tmp_29_fu_519_p1 = a_coeffs_q1.read().range(15-1, 0);
}

void poly_lift::thread_tmp_30_fu_532_p2() {
    tmp_30_fu_532_p2 = (!tmp2_fu_527_p2.read().is_01() || !tmp_29_fu_519_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp2_fu_527_p2.read()) + sc_biguint<15>(tmp_29_fu_519_p1.read()));
}

void poly_lift::thread_tmp_31_fu_538_p3() {
    tmp_31_fu_538_p3 = esl_concat<15,1>(tmp_30_fu_532_p2.read(), ap_const_lv1_0);
}

void poly_lift::thread_tmp_32_fu_546_p2() {
    tmp_32_fu_546_p2 = (!b_coeffs_q0.read().is_01() || !tmp_31_fu_538_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(b_coeffs_q0.read()) + sc_biguint<16>(tmp_31_fu_538_p3.read()));
}

void poly_lift::thread_tmp_33_fu_564_p1() {
    tmp_33_fu_564_p1 = esl_zext<64,10>(i_2_reg_352.read());
}

void poly_lift::thread_tmp_34_fu_523_p1() {
    tmp_34_fu_523_p1 = a_coeffs_q0.read().range(15-1, 0);
}

void poly_lift::thread_tmp_35_fu_569_p2() {
    tmp_35_fu_569_p2 = (!ap_const_lv16_1.is_01())? sc_lv<16>(): b_coeffs_q1.read() << (unsigned short)ap_const_lv16_1.to_uint();
}

void poly_lift::thread_tmp_36_fu_579_p3() {
    tmp_36_fu_579_p3 = esl_concat<7,1>(tmp_37_fu_575_p1.read(), ap_const_lv1_0);
}

void poly_lift::thread_tmp_37_fu_575_p1() {
    tmp_37_fu_575_p1 = b_coeffs_q1.read().range(7-1, 0);
}

void poly_lift::thread_tmp_37_i_cast_fu_895_p2() {
    tmp_37_i_cast_fu_895_p2 = (!ap_const_lv13_0.is_01() || !tmp_52_fu_885_p4.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_biguint<13>(tmp_52_fu_885_p4.read()));
}

void poly_lift::thread_tmp_38_fu_587_p1() {
    tmp_38_fu_587_p1 = b_coeffs_q0.read().range(8-1, 0);
}

void poly_lift::thread_tmp_39_fu_599_p3() {
    tmp_39_fu_599_p3 = esl_concat<3,1>(tmp_49_fu_595_p1.read(), ap_const_lv1_0);
}

void poly_lift::thread_tmp_39_i_fu_921_p3() {
    tmp_39_i_fu_921_p3 = esl_concat<3,13>(tmp_55_fu_911_p4.read(), tmp_54_fu_905_p2.read());
}

void poly_lift::thread_tmp_3_cast_fu_427_p1() {
    tmp_3_cast_fu_427_p1 = esl_zext<16,2>(grp_fu_385_p2.read());
}

void poly_lift::thread_tmp_40_fu_611_p3() {
    tmp_40_fu_611_p3 = esl_concat<1,1>(tmp_50_fu_607_p1.read(), ap_const_lv1_0);
}

void poly_lift::thread_tmp_41_fu_591_p1() {
    tmp_41_fu_591_p1 = b_coeffs_q0.read().range(4-1, 0);
}

void poly_lift::thread_tmp_42_fu_679_p2() {
    tmp_42_fu_679_p2 = (!tmp_39_fu_599_p3.read().is_01() || !tmp_41_fu_591_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_39_fu_599_p3.read()) + sc_biguint<4>(tmp_41_fu_591_p1.read()));
}

void poly_lift::thread_tmp_43_fu_685_p4() {
    tmp_43_fu_685_p4 = a_assign_fu_623_p2.read().range(11, 8);
}

void poly_lift::thread_tmp_44_fu_695_p4() {
    tmp_44_fu_695_p4 = a_assign_fu_623_p2.read().range(9, 8);
}

void poly_lift::thread_tmp_45_fu_705_p2() {
    tmp_45_fu_705_p2 = (!tmp_40_fu_611_p3.read().is_01() || !tmp_51_fu_619_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_40_fu_611_p3.read()) + sc_biguint<2>(tmp_51_fu_619_p1.read()));
}

void poly_lift::thread_tmp_46_fu_737_p2() {
    tmp_46_fu_737_p2 = (!tmp_45_fu_705_p2.read().is_01() || !tmp_44_fu_695_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_45_fu_705_p2.read()) + sc_biguint<2>(tmp_44_fu_695_p4.read()));
}

void poly_lift::thread_tmp_47_fu_743_p4() {
    tmp_47_fu_743_p4 = tmp_56_fu_653_p2.read().range(5, 4);
}

void poly_lift::thread_tmp_49_fu_595_p1() {
    tmp_49_fu_595_p1 = b_coeffs_q1.read().range(3-1, 0);
}

void poly_lift::thread_tmp_50_fu_607_p1() {
    tmp_50_fu_607_p1 = b_coeffs_q1.read().range(1-1, 0);
}

void poly_lift::thread_tmp_51_fu_619_p1() {
    tmp_51_fu_619_p1 = b_coeffs_q0.read().range(2-1, 0);
}

void poly_lift::thread_tmp_52_fu_885_p4() {
    tmp_52_fu_885_p4 = b_coeffs_q1.read().range(13, 1);
}

void poly_lift::thread_tmp_53_fu_635_p4() {
    tmp_53_fu_635_p4 = a_assign_fu_623_p2.read().range(15, 8);
}

void poly_lift::thread_tmp_54_fu_905_p2() {
    tmp_54_fu_905_p2 = (tmp_60_fu_901_p1.read() | tmp_37_i_cast_fu_895_p2.read());
}

void poly_lift::thread_tmp_55_fu_911_p4() {
    tmp_55_fu_911_p4 = b_coeffs_q1.read().range(15, 13);
}

void poly_lift::thread_tmp_56_fu_653_p2() {
    tmp_56_fu_653_p2 = (!a_assign_cast_fu_629_p2.read().is_01() || !tmp_53_fu_635_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(a_assign_cast_fu_629_p2.read()) + sc_biguint<8>(tmp_53_fu_635_p4.read()));
}

void poly_lift::thread_tmp_57_fu_665_p4() {
    tmp_57_fu_665_p4 = r_fu_659_p2.read().range(8, 4);
}

void poly_lift::thread_tmp_58_fu_777_p4() {
    tmp_58_fu_777_p4 = r_2_fu_772_p2.read().range(3, 2);
}

void poly_lift::thread_tmp_59_fu_811_p3() {
    tmp_59_fu_811_p3 = t_fu_805_p2.read().range(2, 2);
}

void poly_lift::thread_tmp_60_fu_901_p1() {
    tmp_60_fu_901_p1 = b_coeffs_q1.read().range(13-1, 0);
}

void poly_lift::thread_tmp_61_fu_973_p1() {
    tmp_61_fu_973_p1 = tmp_238_i_fu_967_p2.read().range(13-1, 0);
}

void poly_lift::thread_tmp_62_fu_958_p1() {
    tmp_62_fu_958_p1 = tmp_236_i_fu_952_p2.read().range(13-1, 0);
}

void poly_lift::thread_tmp_6_fu_431_p1() {
    tmp_6_fu_431_p1 =  (sc_lv<2>) (tmp_6_fu_431_p10.read());
}

void poly_lift::thread_tmp_6_fu_431_p10() {
    tmp_6_fu_431_p10 = esl_zext<16,2>(zj_reg_328.read());
}

void poly_lift::thread_tmp_7_fu_416_p1() {
    tmp_7_fu_416_p1 = esl_zext<64,10>(i_reg_317.read());
}

void poly_lift::thread_tmp_9_fu_459_p2() {
    tmp_9_fu_459_p2 = (!tmp1_reg_1101.read().is_01() || !tmp_1_reg_298.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp1_reg_1101.read()) + sc_biguint<16>(tmp_1_reg_298.read()));
}

void poly_lift::thread_tmp_fu_396_p2() {
    tmp_fu_396_p2 = (!a_coeffs_q0.read().is_01() || !a_coeffs_load_reg_1028.read().is_01())? sc_lv<16>(): (sc_biguint<16>(a_coeffs_q0.read()) + sc_bigint<16>(a_coeffs_load_reg_1028.read()));
}

void poly_lift::thread_tmp_i3_fu_880_p1() {
    tmp_i3_fu_880_p1 = esl_zext<64,10>(i_i_reg_363.read());
}

void poly_lift::thread_tmp_i6_fu_930_p2() {
    tmp_i6_fu_930_p2 = (!i_i5_reg_374.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(i_i5_reg_374.read() == ap_const_lv10_0);
}

void poly_lift::thread_tmp_i7_fu_942_p1() {
    tmp_i7_fu_942_p1 = esl_zext<64,10>(i_8_fu_936_p2.read());
}

void poly_lift::thread_tmp_i_cast_27_fu_649_p1() {
    tmp_i_cast_27_fu_649_p1 = esl_zext<9,8>(a_assign_cast_fu_629_p2.read());
}

void poly_lift::thread_tmp_i_cast_fu_645_p1() {
    tmp_i_cast_fu_645_p1 = esl_zext<9,8>(tmp_53_fu_635_p4.read());
}

void poly_lift::thread_zj_cast9_fu_402_p1() {
    zj_cast9_fu_402_p1 = esl_zext<3,2>(zj_reg_328.read());
}

void poly_lift::thread_zj_cast_fu_406_p1() {
    zj_cast_fu_406_p1 = esl_zext<16,2>(zj_reg_328.read());
}

void poly_lift::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond2_fu_410_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_465_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_552_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i_fu_868_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i6_fu_930_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state21;
            } else {
                ap_NS_fsm = ap_ST_fsm_state20;
            }
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

