// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "poly_Sq_frombytes_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic poly_Sq_frombytes_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic poly_Sq_frombytes_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state1 = "1";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state2 = "10";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state3 = "100";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state4 = "1000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state5 = "10000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state6 = "100000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state8 = "10000000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state9 = "100000000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<13> poly_Sq_frombytes_1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_7 = "111";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_9 = "1001";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_1 = "1";
const sc_lv<1> poly_Sq_frombytes_1::ap_const_lv1_0 = "0";
const sc_lv<1> poly_Sq_frombytes_1::ap_const_lv1_1 = "1";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_2 = "10";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_3 = "11";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_4 = "100";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_5 = "101";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_6 = "110";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_A = "1010";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_B = "1011";
const sc_lv<7> poly_Sq_frombytes_1::ap_const_lv7_0 = "0000000";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_8 = "1000";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_0 = "00000000000";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_587 = "10110000111";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_588 = "10110001000";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_589 = "10110001001";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_586 = "10110000110";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_2BB = "1010111011";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_2BA = "1010111010";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_584 = "10110000100";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_585 = "10110000101";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_2B9 = "1010111001";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_583 = "10110000011";
const sc_lv<64> poly_Sq_frombytes_1::ap_const_lv64_2B8 = "1010111000";
const sc_lv<32> poly_Sq_frombytes_1::ap_const_lv32_C = "1100";
const sc_lv<7> poly_Sq_frombytes_1::ap_const_lv7_57 = "1010111";
const sc_lv<7> poly_Sq_frombytes_1::ap_const_lv7_1 = "1";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_118 = "100011000";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_119 = "100011001";
const sc_lv<3> poly_Sq_frombytes_1::ap_const_lv3_0 = "000";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_11A = "100011010";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_11B = "100011011";
const sc_lv<10> poly_Sq_frombytes_1::ap_const_lv10_1 = "1";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_11C = "100011100";
const sc_lv<10> poly_Sq_frombytes_1::ap_const_lv10_2 = "10";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_11D = "100011101";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_11E = "100011110";
const sc_lv<10> poly_Sq_frombytes_1::ap_const_lv10_3 = "11";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_11F = "100011111";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_120 = "100100000";
const sc_lv<4> poly_Sq_frombytes_1::ap_const_lv4_0 = "0000";
const sc_lv<10> poly_Sq_frombytes_1::ap_const_lv10_4 = "100";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_121 = "100100001";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_122 = "100100010";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_D = "1101";
const sc_lv<10> poly_Sq_frombytes_1::ap_const_lv10_5 = "101";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_123 = "100100011";
const sc_lv<11> poly_Sq_frombytes_1::ap_const_lv11_124 = "100100100";
const sc_lv<2> poly_Sq_frombytes_1::ap_const_lv2_0 = "00";
const sc_lv<10> poly_Sq_frombytes_1::ap_const_lv10_6 = "110";
const sc_lv<10> poly_Sq_frombytes_1::ap_const_lv10_7 = "111";
const bool poly_Sq_frombytes_1::ap_const_boolean_1 = true;

poly_Sq_frombytes_1::poly_Sq_frombytes_1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_484_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( sum_cast_fu_502_p1 );
    sensitive << ( sum4_cast_fu_554_p1 );
    sensitive << ( sum8_cast_fu_638_p1 );
    sensitive << ( sum3_cast_fu_686_p1 );
    sensitive << ( sum7_cast_fu_770_p1 );
    sensitive << ( sum10_cast_fu_854_p1 );
    sensitive << ( sum12_cast_fu_918_p1 );

    SC_METHOD(thread_a_address1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_484_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( sum2_cast_fu_513_p1 );
    sensitive << ( sum6_cast_fu_565_p1 );
    sensitive << ( sum1_cast_fu_675_p1 );
    sensitive << ( sum5_cast_fu_759_p1 );
    sensitive << ( sum9_cast_fu_843_p1 );
    sensitive << ( sum11_cast_fu_907_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_484_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_a_ce1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_484_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_exitcond_fu_484_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_437 );

    SC_METHOD(thread_grp_fu_461_p4);
    sensitive << ( a_q1 );

    SC_METHOD(thread_next_mul_fu_859_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_r_coeffs_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_52_fu_543_p1 );
    sensitive << ( tmp_60_fu_617_p1 );
    sensitive << ( tmp_73_fu_664_p1 );
    sensitive << ( tmp_81_fu_738_p1 );
    sensitive << ( tmp_89_fu_822_p1 );
    sensitive << ( tmp_96_fu_886_p1 );
    sensitive << ( tmp_104_fu_970_p1 );

    SC_METHOD(thread_r_coeffs_address1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_110_fu_1003_p1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_r_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_r_coeffs_ce1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_r_coeffs_d0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_50_fu_530_p1 );
    sensitive << ( tmp_83_cast_fu_607_p1 );
    sensitive << ( tmp_92_cast_fu_654_p1 );
    sensitive << ( tmp_106_cast_fu_728_p1 );
    sensitive << ( tmp_120_cast_fu_812_p1 );
    sensitive << ( tmp_129_cast_fu_876_p1 );
    sensitive << ( tmp_143_cast_fu_960_p1 );
    sensitive << ( tmp_52_cast_fu_1071_p1 );

    SC_METHOD(thread_r_coeffs_d1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_151_cast_fu_993_p1 );
    sensitive << ( tmp_47_cast_fu_1049_p1 );
    sensitive << ( tmp_60_cast_fu_1113_p1 );
    sensitive << ( tmp_46_fu_1129_p1 );

    SC_METHOD(thread_r_coeffs_we0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_r_coeffs_we1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_sum10_cast_fu_854_p1);
    sensitive << ( sum10_fu_848_p2 );

    SC_METHOD(thread_sum10_fu_848_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum11_cast_fu_907_p1);
    sensitive << ( sum11_fu_901_p2 );

    SC_METHOD(thread_sum11_fu_901_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum12_cast_fu_918_p1);
    sensitive << ( sum12_fu_912_p2 );

    SC_METHOD(thread_sum12_fu_912_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum1_cast_fu_675_p1);
    sensitive << ( sum1_fu_669_p2 );

    SC_METHOD(thread_sum1_fu_669_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum2_cast_fu_513_p1);
    sensitive << ( sum2_fu_507_p2 );

    SC_METHOD(thread_sum2_fu_507_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum3_cast_fu_686_p1);
    sensitive << ( sum3_fu_680_p2 );

    SC_METHOD(thread_sum3_fu_680_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum4_cast_fu_554_p1);
    sensitive << ( sum4_fu_548_p2 );

    SC_METHOD(thread_sum4_fu_548_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum5_cast_fu_759_p1);
    sensitive << ( sum5_fu_753_p2 );

    SC_METHOD(thread_sum5_fu_753_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum6_cast_fu_565_p1);
    sensitive << ( sum6_fu_559_p2 );

    SC_METHOD(thread_sum6_fu_559_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum7_cast_fu_770_p1);
    sensitive << ( sum7_fu_764_p2 );

    SC_METHOD(thread_sum7_fu_764_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum8_cast_fu_638_p1);
    sensitive << ( sum8_fu_632_p2 );

    SC_METHOD(thread_sum8_fu_632_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum9_cast_fu_843_p1);
    sensitive << ( sum9_fu_837_p2 );

    SC_METHOD(thread_sum9_fu_837_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_sum_cast_fu_502_p1);
    sensitive << ( sum_fu_496_p2 );

    SC_METHOD(thread_sum_fu_496_p2);
    sensitive << ( phi_mul_reg_449 );

    SC_METHOD(thread_tmp_100_fu_938_p3);
    sensitive << ( tmp_108_fu_923_p1 );

    SC_METHOD(thread_tmp_101_fu_946_p2);
    sensitive << ( tmp_100_fu_938_p3 );
    sensitive << ( tmp_98_fu_926_p3 );

    SC_METHOD(thread_tmp_102_fu_952_p3);
    sensitive << ( tmp_113_fu_934_p1 );
    sensitive << ( tmp_101_fu_946_p2 );

    SC_METHOD(thread_tmp_103_fu_965_p2);
    sensitive << ( tmp_51_reg_1162 );

    SC_METHOD(thread_tmp_104_fu_970_p1);
    sensitive << ( tmp_103_fu_965_p2 );

    SC_METHOD(thread_tmp_105_fu_975_p4);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_106_cast_fu_728_p1);
    sensitive << ( tmp_79_fu_720_p3 );

    SC_METHOD(thread_tmp_106_fu_985_p3);
    sensitive << ( a_q0 );
    sensitive << ( tmp_105_fu_975_p4 );

    SC_METHOD(thread_tmp_107_fu_702_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_108_fu_923_p1);
    sensitive << ( tmp_97_reg_1248 );

    SC_METHOD(thread_tmp_109_fu_998_p2);
    sensitive << ( tmp_51_reg_1162 );

    SC_METHOD(thread_tmp_110_fu_1003_p1);
    sensitive << ( tmp_109_fu_998_p2 );

    SC_METHOD(thread_tmp_111_fu_786_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_112_fu_865_p1);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_113_fu_934_p1);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_120_cast_fu_812_p1);
    sensitive << ( tmp_87_fu_804_p3 );

    SC_METHOD(thread_tmp_129_cast_fu_876_p1);
    sensitive << ( tmp_91_fu_869_p3 );

    SC_METHOD(thread_tmp_143_cast_fu_960_p1);
    sensitive << ( tmp_102_fu_952_p3 );

    SC_METHOD(thread_tmp_151_cast_fu_993_p1);
    sensitive << ( tmp_106_fu_985_p3 );

    SC_METHOD(thread_tmp_36_fu_1015_p3);
    sensitive << ( reg_479 );

    SC_METHOD(thread_tmp_37_fu_1041_p3);
    sensitive << ( tmp_63_fu_1023_p1 );
    sensitive << ( tmp_58_fu_1035_p2 );

    SC_METHOD(thread_tmp_38_fu_1054_p4);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_40_fu_1122_p3);
    sensitive << ( a_q1 );
    sensitive << ( tmp_74_reg_1303 );

    SC_METHOD(thread_tmp_42_fu_1064_p3);
    sensitive << ( tmp_66_reg_1278 );
    sensitive << ( tmp_38_fu_1054_p4 );

    SC_METHOD(thread_tmp_44_fu_1084_p3);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_45_fu_1106_p3);
    sensitive << ( tmp_70_reg_1293 );
    sensitive << ( tmp_65_fu_1100_p2 );

    SC_METHOD(thread_tmp_46_fu_1129_p1);
    sensitive << ( tmp_40_fu_1122_p3 );

    SC_METHOD(thread_tmp_47_cast_fu_1049_p1);
    sensitive << ( tmp_37_fu_1041_p3 );

    SC_METHOD(thread_tmp_49_fu_522_p3);
    sensitive << ( a_q0 );
    sensitive << ( tmp_76_fu_518_p1 );

    SC_METHOD(thread_tmp_50_fu_530_p1);
    sensitive << ( tmp_49_fu_522_p3 );

    SC_METHOD(thread_tmp_51_fu_535_p3);
    sensitive << ( i_reg_437 );

    SC_METHOD(thread_tmp_52_cast_fu_1071_p1);
    sensitive << ( tmp_42_fu_1064_p3 );

    SC_METHOD(thread_tmp_52_fu_543_p1);
    sensitive << ( tmp_51_fu_535_p3 );

    SC_METHOD(thread_tmp_54_fu_573_p3);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_55_fu_599_p3);
    sensitive << ( tmp_84_fu_581_p1 );
    sensitive << ( tmp_68_fu_593_p2 );

    SC_METHOD(thread_tmp_56_fu_612_p2);
    sensitive << ( tmp_51_reg_1162 );

    SC_METHOD(thread_tmp_57_fu_1027_p3);
    sensitive << ( tmp_59_fu_1012_p1 );

    SC_METHOD(thread_tmp_58_fu_1035_p2);
    sensitive << ( tmp_57_fu_1027_p3 );
    sensitive << ( tmp_36_fu_1015_p3 );

    SC_METHOD(thread_tmp_59_fu_1012_p1);
    sensitive << ( tmp_reg_1263 );

    SC_METHOD(thread_tmp_60_cast_fu_1113_p1);
    sensitive << ( tmp_45_fu_1106_p3 );

    SC_METHOD(thread_tmp_60_fu_617_p1);
    sensitive << ( tmp_56_fu_612_p2 );

    SC_METHOD(thread_tmp_62_fu_1080_p1);
    sensitive << ( grp_fu_461_p4 );

    SC_METHOD(thread_tmp_63_fu_1023_p1);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_64_fu_1092_p3);
    sensitive << ( tmp_62_fu_1080_p1 );

    SC_METHOD(thread_tmp_65_fu_1100_p2);
    sensitive << ( tmp_64_fu_1092_p3 );
    sensitive << ( tmp_44_fu_1084_p3 );

    SC_METHOD(thread_tmp_66_fu_1008_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_67_fu_585_p3);
    sensitive << ( tmp_71_fu_570_p1 );

    SC_METHOD(thread_tmp_68_fu_593_p2);
    sensitive << ( tmp_67_fu_585_p3 );
    sensitive << ( tmp_54_fu_573_p3 );

    SC_METHOD(thread_tmp_69_fu_647_p3);
    sensitive << ( tmp_61_reg_1188 );
    sensitive << ( tmp_92_fu_643_p1 );

    SC_METHOD(thread_tmp_70_fu_1076_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_71_fu_570_p1);
    sensitive << ( tmp_53_reg_1173 );

    SC_METHOD(thread_tmp_72_fu_659_p2);
    sensitive << ( tmp_51_reg_1162 );

    SC_METHOD(thread_tmp_73_fu_664_p1);
    sensitive << ( tmp_72_fu_659_p2 );

    SC_METHOD(thread_tmp_74_fu_1118_p1);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_75_fu_694_p3);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_76_fu_518_p1);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_77_fu_706_p3);
    sensitive << ( tmp_93_fu_691_p1 );

    SC_METHOD(thread_tmp_78_fu_714_p2);
    sensitive << ( tmp_77_fu_706_p3 );
    sensitive << ( tmp_75_fu_694_p3 );

    SC_METHOD(thread_tmp_79_fu_720_p3);
    sensitive << ( tmp_107_fu_702_p1 );
    sensitive << ( tmp_78_fu_714_p2 );

    SC_METHOD(thread_tmp_80_fu_733_p2);
    sensitive << ( tmp_51_reg_1162 );

    SC_METHOD(thread_tmp_81_fu_738_p1);
    sensitive << ( tmp_80_fu_733_p2 );

    SC_METHOD(thread_tmp_83_cast_fu_607_p1);
    sensitive << ( tmp_55_fu_599_p3 );

    SC_METHOD(thread_tmp_83_fu_778_p3);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_84_fu_581_p1);
    sensitive << ( a_q1 );

    SC_METHOD(thread_tmp_85_fu_790_p3);
    sensitive << ( tmp_94_fu_775_p1 );

    SC_METHOD(thread_tmp_86_fu_798_p2);
    sensitive << ( tmp_85_fu_790_p3 );
    sensitive << ( tmp_83_fu_778_p3 );

    SC_METHOD(thread_tmp_87_fu_804_p3);
    sensitive << ( tmp_111_fu_786_p1 );
    sensitive << ( tmp_86_fu_798_p2 );

    SC_METHOD(thread_tmp_88_fu_817_p2);
    sensitive << ( tmp_51_reg_1162 );

    SC_METHOD(thread_tmp_89_fu_822_p1);
    sensitive << ( tmp_88_fu_817_p2 );

    SC_METHOD(thread_tmp_91_fu_869_p3);
    sensitive << ( tmp_90_reg_1228 );
    sensitive << ( tmp_112_fu_865_p1 );

    SC_METHOD(thread_tmp_92_cast_fu_654_p1);
    sensitive << ( tmp_69_fu_647_p3 );

    SC_METHOD(thread_tmp_92_fu_643_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_tmp_93_fu_691_p1);
    sensitive << ( tmp_99_reg_1198 );

    SC_METHOD(thread_tmp_94_fu_775_p1);
    sensitive << ( tmp_82_reg_1213 );

    SC_METHOD(thread_tmp_95_fu_881_p2);
    sensitive << ( tmp_51_reg_1162 );

    SC_METHOD(thread_tmp_96_fu_886_p1);
    sensitive << ( tmp_95_fu_881_p2 );

    SC_METHOD(thread_tmp_98_fu_926_p3);
    sensitive << ( reg_479 );

    SC_METHOD(thread_tmp_s_fu_490_p2);
    sensitive << ( i_reg_437 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_484_p2 );

    ap_CS_fsm = "0000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "poly_Sq_frombytes_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, r_coeffs_address0, "(port)r_coeffs_address0");
    sc_trace(mVcdFile, r_coeffs_ce0, "(port)r_coeffs_ce0");
    sc_trace(mVcdFile, r_coeffs_we0, "(port)r_coeffs_we0");
    sc_trace(mVcdFile, r_coeffs_d0, "(port)r_coeffs_d0");
    sc_trace(mVcdFile, r_coeffs_address1, "(port)r_coeffs_address1");
    sc_trace(mVcdFile, r_coeffs_ce1, "(port)r_coeffs_ce1");
    sc_trace(mVcdFile, r_coeffs_we1, "(port)r_coeffs_we1");
    sc_trace(mVcdFile, r_coeffs_d1, "(port)r_coeffs_d1");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, a_address1, "(port)a_address1");
    sc_trace(mVcdFile, a_ce1, "(port)a_ce1");
    sc_trace(mVcdFile, a_q1, "(port)a_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_479, "reg_479");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_s_fu_490_p2, "tmp_s_fu_490_p2");
    sc_trace(mVcdFile, tmp_s_reg_1137, "tmp_s_reg_1137");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_fu_484_p2, "exitcond_fu_484_p2");
    sc_trace(mVcdFile, tmp_51_fu_535_p3, "tmp_51_fu_535_p3");
    sc_trace(mVcdFile, tmp_51_reg_1162, "tmp_51_reg_1162");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_fu_461_p4, "grp_fu_461_p4");
    sc_trace(mVcdFile, tmp_53_reg_1173, "tmp_53_reg_1173");
    sc_trace(mVcdFile, tmp_61_reg_1188, "tmp_61_reg_1188");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_99_reg_1198, "tmp_99_reg_1198");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_82_reg_1213, "tmp_82_reg_1213");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_90_reg_1228, "tmp_90_reg_1228");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, next_mul_fu_859_p2, "next_mul_fu_859_p2");
    sc_trace(mVcdFile, next_mul_reg_1243, "next_mul_reg_1243");
    sc_trace(mVcdFile, tmp_97_reg_1248, "tmp_97_reg_1248");
    sc_trace(mVcdFile, tmp_reg_1263, "tmp_reg_1263");
    sc_trace(mVcdFile, tmp_66_fu_1008_p1, "tmp_66_fu_1008_p1");
    sc_trace(mVcdFile, tmp_66_reg_1278, "tmp_66_reg_1278");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_70_fu_1076_p1, "tmp_70_fu_1076_p1");
    sc_trace(mVcdFile, tmp_70_reg_1293, "tmp_70_reg_1293");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_74_fu_1118_p1, "tmp_74_fu_1118_p1");
    sc_trace(mVcdFile, tmp_74_reg_1303, "tmp_74_reg_1303");
    sc_trace(mVcdFile, i_reg_437, "i_reg_437");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, phi_mul_reg_449, "phi_mul_reg_449");
    sc_trace(mVcdFile, sum_cast_fu_502_p1, "sum_cast_fu_502_p1");
    sc_trace(mVcdFile, sum2_cast_fu_513_p1, "sum2_cast_fu_513_p1");
    sc_trace(mVcdFile, tmp_52_fu_543_p1, "tmp_52_fu_543_p1");
    sc_trace(mVcdFile, sum4_cast_fu_554_p1, "sum4_cast_fu_554_p1");
    sc_trace(mVcdFile, sum6_cast_fu_565_p1, "sum6_cast_fu_565_p1");
    sc_trace(mVcdFile, tmp_60_fu_617_p1, "tmp_60_fu_617_p1");
    sc_trace(mVcdFile, sum8_cast_fu_638_p1, "sum8_cast_fu_638_p1");
    sc_trace(mVcdFile, tmp_73_fu_664_p1, "tmp_73_fu_664_p1");
    sc_trace(mVcdFile, sum1_cast_fu_675_p1, "sum1_cast_fu_675_p1");
    sc_trace(mVcdFile, sum3_cast_fu_686_p1, "sum3_cast_fu_686_p1");
    sc_trace(mVcdFile, tmp_81_fu_738_p1, "tmp_81_fu_738_p1");
    sc_trace(mVcdFile, sum5_cast_fu_759_p1, "sum5_cast_fu_759_p1");
    sc_trace(mVcdFile, sum7_cast_fu_770_p1, "sum7_cast_fu_770_p1");
    sc_trace(mVcdFile, tmp_89_fu_822_p1, "tmp_89_fu_822_p1");
    sc_trace(mVcdFile, sum9_cast_fu_843_p1, "sum9_cast_fu_843_p1");
    sc_trace(mVcdFile, sum10_cast_fu_854_p1, "sum10_cast_fu_854_p1");
    sc_trace(mVcdFile, tmp_96_fu_886_p1, "tmp_96_fu_886_p1");
    sc_trace(mVcdFile, sum11_cast_fu_907_p1, "sum11_cast_fu_907_p1");
    sc_trace(mVcdFile, sum12_cast_fu_918_p1, "sum12_cast_fu_918_p1");
    sc_trace(mVcdFile, tmp_104_fu_970_p1, "tmp_104_fu_970_p1");
    sc_trace(mVcdFile, tmp_110_fu_1003_p1, "tmp_110_fu_1003_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, tmp_50_fu_530_p1, "tmp_50_fu_530_p1");
    sc_trace(mVcdFile, tmp_83_cast_fu_607_p1, "tmp_83_cast_fu_607_p1");
    sc_trace(mVcdFile, tmp_92_cast_fu_654_p1, "tmp_92_cast_fu_654_p1");
    sc_trace(mVcdFile, tmp_106_cast_fu_728_p1, "tmp_106_cast_fu_728_p1");
    sc_trace(mVcdFile, tmp_120_cast_fu_812_p1, "tmp_120_cast_fu_812_p1");
    sc_trace(mVcdFile, tmp_129_cast_fu_876_p1, "tmp_129_cast_fu_876_p1");
    sc_trace(mVcdFile, tmp_143_cast_fu_960_p1, "tmp_143_cast_fu_960_p1");
    sc_trace(mVcdFile, tmp_151_cast_fu_993_p1, "tmp_151_cast_fu_993_p1");
    sc_trace(mVcdFile, tmp_47_cast_fu_1049_p1, "tmp_47_cast_fu_1049_p1");
    sc_trace(mVcdFile, tmp_52_cast_fu_1071_p1, "tmp_52_cast_fu_1071_p1");
    sc_trace(mVcdFile, tmp_60_cast_fu_1113_p1, "tmp_60_cast_fu_1113_p1");
    sc_trace(mVcdFile, tmp_46_fu_1129_p1, "tmp_46_fu_1129_p1");
    sc_trace(mVcdFile, sum_fu_496_p2, "sum_fu_496_p2");
    sc_trace(mVcdFile, sum2_fu_507_p2, "sum2_fu_507_p2");
    sc_trace(mVcdFile, tmp_76_fu_518_p1, "tmp_76_fu_518_p1");
    sc_trace(mVcdFile, tmp_49_fu_522_p3, "tmp_49_fu_522_p3");
    sc_trace(mVcdFile, sum4_fu_548_p2, "sum4_fu_548_p2");
    sc_trace(mVcdFile, sum6_fu_559_p2, "sum6_fu_559_p2");
    sc_trace(mVcdFile, tmp_71_fu_570_p1, "tmp_71_fu_570_p1");
    sc_trace(mVcdFile, tmp_67_fu_585_p3, "tmp_67_fu_585_p3");
    sc_trace(mVcdFile, tmp_54_fu_573_p3, "tmp_54_fu_573_p3");
    sc_trace(mVcdFile, tmp_84_fu_581_p1, "tmp_84_fu_581_p1");
    sc_trace(mVcdFile, tmp_68_fu_593_p2, "tmp_68_fu_593_p2");
    sc_trace(mVcdFile, tmp_55_fu_599_p3, "tmp_55_fu_599_p3");
    sc_trace(mVcdFile, tmp_56_fu_612_p2, "tmp_56_fu_612_p2");
    sc_trace(mVcdFile, sum8_fu_632_p2, "sum8_fu_632_p2");
    sc_trace(mVcdFile, tmp_92_fu_643_p1, "tmp_92_fu_643_p1");
    sc_trace(mVcdFile, tmp_69_fu_647_p3, "tmp_69_fu_647_p3");
    sc_trace(mVcdFile, tmp_72_fu_659_p2, "tmp_72_fu_659_p2");
    sc_trace(mVcdFile, sum1_fu_669_p2, "sum1_fu_669_p2");
    sc_trace(mVcdFile, sum3_fu_680_p2, "sum3_fu_680_p2");
    sc_trace(mVcdFile, tmp_93_fu_691_p1, "tmp_93_fu_691_p1");
    sc_trace(mVcdFile, tmp_77_fu_706_p3, "tmp_77_fu_706_p3");
    sc_trace(mVcdFile, tmp_75_fu_694_p3, "tmp_75_fu_694_p3");
    sc_trace(mVcdFile, tmp_107_fu_702_p1, "tmp_107_fu_702_p1");
    sc_trace(mVcdFile, tmp_78_fu_714_p2, "tmp_78_fu_714_p2");
    sc_trace(mVcdFile, tmp_79_fu_720_p3, "tmp_79_fu_720_p3");
    sc_trace(mVcdFile, tmp_80_fu_733_p2, "tmp_80_fu_733_p2");
    sc_trace(mVcdFile, sum5_fu_753_p2, "sum5_fu_753_p2");
    sc_trace(mVcdFile, sum7_fu_764_p2, "sum7_fu_764_p2");
    sc_trace(mVcdFile, tmp_94_fu_775_p1, "tmp_94_fu_775_p1");
    sc_trace(mVcdFile, tmp_85_fu_790_p3, "tmp_85_fu_790_p3");
    sc_trace(mVcdFile, tmp_83_fu_778_p3, "tmp_83_fu_778_p3");
    sc_trace(mVcdFile, tmp_111_fu_786_p1, "tmp_111_fu_786_p1");
    sc_trace(mVcdFile, tmp_86_fu_798_p2, "tmp_86_fu_798_p2");
    sc_trace(mVcdFile, tmp_87_fu_804_p3, "tmp_87_fu_804_p3");
    sc_trace(mVcdFile, tmp_88_fu_817_p2, "tmp_88_fu_817_p2");
    sc_trace(mVcdFile, sum9_fu_837_p2, "sum9_fu_837_p2");
    sc_trace(mVcdFile, sum10_fu_848_p2, "sum10_fu_848_p2");
    sc_trace(mVcdFile, tmp_112_fu_865_p1, "tmp_112_fu_865_p1");
    sc_trace(mVcdFile, tmp_91_fu_869_p3, "tmp_91_fu_869_p3");
    sc_trace(mVcdFile, tmp_95_fu_881_p2, "tmp_95_fu_881_p2");
    sc_trace(mVcdFile, sum11_fu_901_p2, "sum11_fu_901_p2");
    sc_trace(mVcdFile, sum12_fu_912_p2, "sum12_fu_912_p2");
    sc_trace(mVcdFile, tmp_108_fu_923_p1, "tmp_108_fu_923_p1");
    sc_trace(mVcdFile, tmp_100_fu_938_p3, "tmp_100_fu_938_p3");
    sc_trace(mVcdFile, tmp_98_fu_926_p3, "tmp_98_fu_926_p3");
    sc_trace(mVcdFile, tmp_113_fu_934_p1, "tmp_113_fu_934_p1");
    sc_trace(mVcdFile, tmp_101_fu_946_p2, "tmp_101_fu_946_p2");
    sc_trace(mVcdFile, tmp_102_fu_952_p3, "tmp_102_fu_952_p3");
    sc_trace(mVcdFile, tmp_103_fu_965_p2, "tmp_103_fu_965_p2");
    sc_trace(mVcdFile, tmp_105_fu_975_p4, "tmp_105_fu_975_p4");
    sc_trace(mVcdFile, tmp_106_fu_985_p3, "tmp_106_fu_985_p3");
    sc_trace(mVcdFile, tmp_109_fu_998_p2, "tmp_109_fu_998_p2");
    sc_trace(mVcdFile, tmp_59_fu_1012_p1, "tmp_59_fu_1012_p1");
    sc_trace(mVcdFile, tmp_57_fu_1027_p3, "tmp_57_fu_1027_p3");
    sc_trace(mVcdFile, tmp_36_fu_1015_p3, "tmp_36_fu_1015_p3");
    sc_trace(mVcdFile, tmp_63_fu_1023_p1, "tmp_63_fu_1023_p1");
    sc_trace(mVcdFile, tmp_58_fu_1035_p2, "tmp_58_fu_1035_p2");
    sc_trace(mVcdFile, tmp_37_fu_1041_p3, "tmp_37_fu_1041_p3");
    sc_trace(mVcdFile, tmp_38_fu_1054_p4, "tmp_38_fu_1054_p4");
    sc_trace(mVcdFile, tmp_42_fu_1064_p3, "tmp_42_fu_1064_p3");
    sc_trace(mVcdFile, tmp_62_fu_1080_p1, "tmp_62_fu_1080_p1");
    sc_trace(mVcdFile, tmp_64_fu_1092_p3, "tmp_64_fu_1092_p3");
    sc_trace(mVcdFile, tmp_44_fu_1084_p3, "tmp_44_fu_1084_p3");
    sc_trace(mVcdFile, tmp_65_fu_1100_p2, "tmp_65_fu_1100_p2");
    sc_trace(mVcdFile, tmp_45_fu_1106_p3, "tmp_45_fu_1106_p3");
    sc_trace(mVcdFile, tmp_40_fu_1122_p3, "tmp_40_fu_1122_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

poly_Sq_frombytes_1::~poly_Sq_frombytes_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void poly_Sq_frombytes_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_reg_437 = tmp_s_reg_1137.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_437 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        phi_mul_reg_449 = next_mul_reg_1243.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_mul_reg_449 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        reg_479 = a_q1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        reg_479 = a_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        next_mul_reg_1243 = next_mul_fu_859_p2.read();
        tmp_97_reg_1248 = a_q1.read().range(7, 6);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_51_reg_1162 = tmp_51_fu_535_p3.read();
        tmp_53_reg_1173 = a_q1.read().range(7, 5);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp_61_reg_1188 = a_q1.read().range(7, 2);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_66_reg_1278 = tmp_66_fu_1008_p1.read();
        tmp_reg_1263 = a_q0.read().range(7, 7);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        tmp_70_reg_1293 = tmp_70_fu_1076_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_74_reg_1303 = tmp_74_fu_1118_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_82_reg_1213 = a_q0.read().range(7, 4);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_90_reg_1228 = a_q0.read().range(7, 1);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        tmp_99_reg_1198 = a_q0.read().range(7, 7);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        tmp_s_reg_1137 = tmp_s_fu_490_p2.read();
    }
}

void poly_Sq_frombytes_1::thread_a_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        a_address0 =  (sc_lv<11>) (ap_const_lv64_585);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        a_address0 =  (sc_lv<11>) (ap_const_lv64_586);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        a_address0 =  (sc_lv<11>) (sum12_cast_fu_918_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        a_address0 =  (sc_lv<11>) (sum10_cast_fu_854_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        a_address0 =  (sc_lv<11>) (sum7_cast_fu_770_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_address0 =  (sc_lv<11>) (sum3_cast_fu_686_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        a_address0 =  (sc_lv<11>) (sum8_cast_fu_638_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        a_address0 =  (sc_lv<11>) (sum4_cast_fu_554_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_1))) {
        a_address0 =  (sc_lv<11>) (ap_const_lv64_587);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_0))) {
        a_address0 =  (sc_lv<11>) (sum_cast_fu_502_p1.read());
    } else {
        a_address0 = "XXXXXXXXXXX";
    }
}

void poly_Sq_frombytes_1::thread_a_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        a_address1 =  (sc_lv<11>) (ap_const_lv64_583);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        a_address1 =  (sc_lv<11>) (ap_const_lv64_584);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        a_address1 =  (sc_lv<11>) (ap_const_lv64_589);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        a_address1 =  (sc_lv<11>) (sum11_cast_fu_907_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        a_address1 =  (sc_lv<11>) (sum9_cast_fu_843_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        a_address1 =  (sc_lv<11>) (sum5_cast_fu_759_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_address1 =  (sc_lv<11>) (sum1_cast_fu_675_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        a_address1 =  (sc_lv<11>) (sum6_cast_fu_565_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_1))) {
        a_address1 =  (sc_lv<11>) (ap_const_lv64_588);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_0))) {
        a_address1 =  (sc_lv<11>) (sum2_cast_fu_513_p1.read());
    } else {
        a_address1 = "XXXXXXXXXXX";
    }
}

void poly_Sq_frombytes_1::thread_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_a_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        a_ce1 = ap_const_logic_1;
    } else {
        a_ce1 = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void poly_Sq_frombytes_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void poly_Sq_frombytes_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_exitcond_fu_484_p2() {
    exitcond_fu_484_p2 = (!i_reg_437.read().is_01() || !ap_const_lv7_57.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_437.read() == ap_const_lv7_57);
}

void poly_Sq_frombytes_1::thread_grp_fu_461_p4() {
    grp_fu_461_p4 = a_q1.read().range(7, 5);
}

void poly_Sq_frombytes_1::thread_next_mul_fu_859_p2() {
    next_mul_fu_859_p2 = (!ap_const_lv11_D.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_D) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_r_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (ap_const_lv64_2BA);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_104_fu_970_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_96_fu_886_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_89_fu_822_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_81_fu_738_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_73_fu_664_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_60_fu_617_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        r_coeffs_address0 =  (sc_lv<10>) (tmp_52_fu_543_p1.read());
    } else {
        r_coeffs_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void poly_Sq_frombytes_1::thread_r_coeffs_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        r_coeffs_address1 =  (sc_lv<10>) (ap_const_lv64_2B8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        r_coeffs_address1 =  (sc_lv<10>) (ap_const_lv64_2B9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        r_coeffs_address1 =  (sc_lv<10>) (ap_const_lv64_2BB);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_coeffs_address1 =  (sc_lv<10>) (tmp_110_fu_1003_p1.read());
    } else {
        r_coeffs_address1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void poly_Sq_frombytes_1::thread_r_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        r_coeffs_ce0 = ap_const_logic_1;
    } else {
        r_coeffs_ce0 = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_r_coeffs_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        r_coeffs_ce1 = ap_const_logic_1;
    } else {
        r_coeffs_ce1 = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_r_coeffs_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        r_coeffs_d0 = tmp_52_cast_fu_1071_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_coeffs_d0 = tmp_143_cast_fu_960_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        r_coeffs_d0 = tmp_129_cast_fu_876_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        r_coeffs_d0 = tmp_120_cast_fu_812_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        r_coeffs_d0 = tmp_106_cast_fu_728_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        r_coeffs_d0 = tmp_92_cast_fu_654_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        r_coeffs_d0 = tmp_83_cast_fu_607_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        r_coeffs_d0 = tmp_50_fu_530_p1.read();
    } else {
        r_coeffs_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void poly_Sq_frombytes_1::thread_r_coeffs_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        r_coeffs_d1 = tmp_46_fu_1129_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        r_coeffs_d1 = tmp_60_cast_fu_1113_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        r_coeffs_d1 = tmp_47_cast_fu_1049_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_coeffs_d1 = tmp_151_cast_fu_993_p1.read();
    } else {
        r_coeffs_d1 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void poly_Sq_frombytes_1::thread_r_coeffs_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        r_coeffs_we0 = ap_const_logic_1;
    } else {
        r_coeffs_we0 = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_r_coeffs_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        r_coeffs_we1 = ap_const_logic_1;
    } else {
        r_coeffs_we1 = ap_const_logic_0;
    }
}

void poly_Sq_frombytes_1::thread_sum10_cast_fu_854_p1() {
    sum10_cast_fu_854_p1 = esl_zext<64,11>(sum10_fu_848_p2.read());
}

void poly_Sq_frombytes_1::thread_sum10_fu_848_p2() {
    sum10_fu_848_p2 = (!ap_const_lv11_122.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_122) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum11_cast_fu_907_p1() {
    sum11_cast_fu_907_p1 = esl_zext<64,11>(sum11_fu_901_p2.read());
}

void poly_Sq_frombytes_1::thread_sum11_fu_901_p2() {
    sum11_fu_901_p2 = (!ap_const_lv11_123.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_123) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum12_cast_fu_918_p1() {
    sum12_cast_fu_918_p1 = esl_zext<64,11>(sum12_fu_912_p2.read());
}

void poly_Sq_frombytes_1::thread_sum12_fu_912_p2() {
    sum12_fu_912_p2 = (!ap_const_lv11_124.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_124) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum1_cast_fu_675_p1() {
    sum1_cast_fu_675_p1 = esl_zext<64,11>(sum1_fu_669_p2.read());
}

void poly_Sq_frombytes_1::thread_sum1_fu_669_p2() {
    sum1_fu_669_p2 = (!ap_const_lv11_11D.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_11D) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum2_cast_fu_513_p1() {
    sum2_cast_fu_513_p1 = esl_zext<64,11>(sum2_fu_507_p2.read());
}

void poly_Sq_frombytes_1::thread_sum2_fu_507_p2() {
    sum2_fu_507_p2 = (!ap_const_lv11_119.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_119) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum3_cast_fu_686_p1() {
    sum3_cast_fu_686_p1 = esl_zext<64,11>(sum3_fu_680_p2.read());
}

void poly_Sq_frombytes_1::thread_sum3_fu_680_p2() {
    sum3_fu_680_p2 = (!ap_const_lv11_11E.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_11E) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum4_cast_fu_554_p1() {
    sum4_cast_fu_554_p1 = esl_zext<64,11>(sum4_fu_548_p2.read());
}

void poly_Sq_frombytes_1::thread_sum4_fu_548_p2() {
    sum4_fu_548_p2 = (!ap_const_lv11_11A.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_11A) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum5_cast_fu_759_p1() {
    sum5_cast_fu_759_p1 = esl_zext<64,11>(sum5_fu_753_p2.read());
}

void poly_Sq_frombytes_1::thread_sum5_fu_753_p2() {
    sum5_fu_753_p2 = (!ap_const_lv11_11F.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_11F) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum6_cast_fu_565_p1() {
    sum6_cast_fu_565_p1 = esl_zext<64,11>(sum6_fu_559_p2.read());
}

void poly_Sq_frombytes_1::thread_sum6_fu_559_p2() {
    sum6_fu_559_p2 = (!ap_const_lv11_11B.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_11B) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum7_cast_fu_770_p1() {
    sum7_cast_fu_770_p1 = esl_zext<64,11>(sum7_fu_764_p2.read());
}

void poly_Sq_frombytes_1::thread_sum7_fu_764_p2() {
    sum7_fu_764_p2 = (!ap_const_lv11_120.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_120) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum8_cast_fu_638_p1() {
    sum8_cast_fu_638_p1 = esl_zext<64,11>(sum8_fu_632_p2.read());
}

void poly_Sq_frombytes_1::thread_sum8_fu_632_p2() {
    sum8_fu_632_p2 = (!ap_const_lv11_11C.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_11C) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum9_cast_fu_843_p1() {
    sum9_cast_fu_843_p1 = esl_zext<64,11>(sum9_fu_837_p2.read());
}

void poly_Sq_frombytes_1::thread_sum9_fu_837_p2() {
    sum9_fu_837_p2 = (!ap_const_lv11_121.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_121) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_sum_cast_fu_502_p1() {
    sum_cast_fu_502_p1 = esl_zext<64,11>(sum_fu_496_p2.read());
}

void poly_Sq_frombytes_1::thread_sum_fu_496_p2() {
    sum_fu_496_p2 = (!ap_const_lv11_118.is_01() || !phi_mul_reg_449.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_118) + sc_biguint<11>(phi_mul_reg_449.read()));
}

void poly_Sq_frombytes_1::thread_tmp_100_fu_938_p3() {
    tmp_100_fu_938_p3 = esl_concat<2,8>(ap_const_lv2_0, tmp_108_fu_923_p1.read());
}

void poly_Sq_frombytes_1::thread_tmp_101_fu_946_p2() {
    tmp_101_fu_946_p2 = (tmp_100_fu_938_p3.read() | tmp_98_fu_926_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_102_fu_952_p3() {
    tmp_102_fu_952_p3 = esl_concat<3,10>(tmp_113_fu_934_p1.read(), tmp_101_fu_946_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_103_fu_965_p2() {
    tmp_103_fu_965_p2 = (tmp_51_reg_1162.read() | ap_const_lv10_6);
}

void poly_Sq_frombytes_1::thread_tmp_104_fu_970_p1() {
    tmp_104_fu_970_p1 = esl_zext<64,10>(tmp_103_fu_965_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_105_fu_975_p4() {
    tmp_105_fu_975_p4 = a_q1.read().range(7, 3);
}

void poly_Sq_frombytes_1::thread_tmp_106_cast_fu_728_p1() {
    tmp_106_cast_fu_728_p1 = esl_zext<16,13>(tmp_79_fu_720_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_106_fu_985_p3() {
    tmp_106_fu_985_p3 = esl_concat<8,5>(a_q0.read(), tmp_105_fu_975_p4.read());
}

void poly_Sq_frombytes_1::thread_tmp_107_fu_702_p1() {
    tmp_107_fu_702_p1 = a_q0.read().range(4-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_108_fu_923_p1() {
    tmp_108_fu_923_p1 = esl_zext<8,2>(tmp_97_reg_1248.read());
}

void poly_Sq_frombytes_1::thread_tmp_109_fu_998_p2() {
    tmp_109_fu_998_p2 = (tmp_51_reg_1162.read() | ap_const_lv10_7);
}

void poly_Sq_frombytes_1::thread_tmp_110_fu_1003_p1() {
    tmp_110_fu_1003_p1 = esl_zext<64,10>(tmp_109_fu_998_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_111_fu_786_p1() {
    tmp_111_fu_786_p1 = a_q0.read().range(1-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_112_fu_865_p1() {
    tmp_112_fu_865_p1 = a_q1.read().range(6-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_113_fu_934_p1() {
    tmp_113_fu_934_p1 = a_q1.read().range(3-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_120_cast_fu_812_p1() {
    tmp_120_cast_fu_812_p1 = esl_zext<16,13>(tmp_87_fu_804_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_129_cast_fu_876_p1() {
    tmp_129_cast_fu_876_p1 = esl_zext<16,13>(tmp_91_fu_869_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_143_cast_fu_960_p1() {
    tmp_143_cast_fu_960_p1 = esl_zext<16,13>(tmp_102_fu_952_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_151_cast_fu_993_p1() {
    tmp_151_cast_fu_993_p1 = esl_zext<16,13>(tmp_106_fu_985_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_36_fu_1015_p3() {
    tmp_36_fu_1015_p3 = esl_concat<8,1>(reg_479.read(), ap_const_lv1_0);
}

void poly_Sq_frombytes_1::thread_tmp_37_fu_1041_p3() {
    tmp_37_fu_1041_p3 = esl_concat<4,9>(tmp_63_fu_1023_p1.read(), tmp_58_fu_1035_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_38_fu_1054_p4() {
    tmp_38_fu_1054_p4 = a_q0.read().range(7, 2);
}

void poly_Sq_frombytes_1::thread_tmp_40_fu_1122_p3() {
    tmp_40_fu_1122_p3 = esl_concat<5,8>(tmp_74_reg_1303.read(), a_q1.read());
}

void poly_Sq_frombytes_1::thread_tmp_42_fu_1064_p3() {
    tmp_42_fu_1064_p3 = esl_concat<7,6>(tmp_66_reg_1278.read(), tmp_38_fu_1054_p4.read());
}

void poly_Sq_frombytes_1::thread_tmp_44_fu_1084_p3() {
    tmp_44_fu_1084_p3 = esl_concat<8,3>(a_q0.read(), ap_const_lv3_0);
}

void poly_Sq_frombytes_1::thread_tmp_45_fu_1106_p3() {
    tmp_45_fu_1106_p3 = esl_concat<2,11>(tmp_70_reg_1293.read(), tmp_65_fu_1100_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_46_fu_1129_p1() {
    tmp_46_fu_1129_p1 = esl_zext<16,13>(tmp_40_fu_1122_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_47_cast_fu_1049_p1() {
    tmp_47_cast_fu_1049_p1 = esl_zext<16,13>(tmp_37_fu_1041_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_49_fu_522_p3() {
    tmp_49_fu_522_p3 = esl_concat<5,8>(tmp_76_fu_518_p1.read(), a_q0.read());
}

void poly_Sq_frombytes_1::thread_tmp_50_fu_530_p1() {
    tmp_50_fu_530_p1 = esl_zext<16,13>(tmp_49_fu_522_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_51_fu_535_p3() {
    tmp_51_fu_535_p3 = esl_concat<7,3>(i_reg_437.read(), ap_const_lv3_0);
}

void poly_Sq_frombytes_1::thread_tmp_52_cast_fu_1071_p1() {
    tmp_52_cast_fu_1071_p1 = esl_zext<16,13>(tmp_42_fu_1064_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_52_fu_543_p1() {
    tmp_52_fu_543_p1 = esl_zext<64,10>(tmp_51_fu_535_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_54_fu_573_p3() {
    tmp_54_fu_573_p3 = esl_concat<8,3>(a_q0.read(), ap_const_lv3_0);
}

void poly_Sq_frombytes_1::thread_tmp_55_fu_599_p3() {
    tmp_55_fu_599_p3 = esl_concat<2,11>(tmp_84_fu_581_p1.read(), tmp_68_fu_593_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_56_fu_612_p2() {
    tmp_56_fu_612_p2 = (tmp_51_reg_1162.read() | ap_const_lv10_1);
}

void poly_Sq_frombytes_1::thread_tmp_57_fu_1027_p3() {
    tmp_57_fu_1027_p3 = esl_concat<1,8>(ap_const_lv1_0, tmp_59_fu_1012_p1.read());
}

void poly_Sq_frombytes_1::thread_tmp_58_fu_1035_p2() {
    tmp_58_fu_1035_p2 = (tmp_57_fu_1027_p3.read() | tmp_36_fu_1015_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_59_fu_1012_p1() {
    tmp_59_fu_1012_p1 = esl_zext<8,1>(tmp_reg_1263.read());
}

void poly_Sq_frombytes_1::thread_tmp_60_cast_fu_1113_p1() {
    tmp_60_cast_fu_1113_p1 = esl_zext<16,13>(tmp_45_fu_1106_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_60_fu_617_p1() {
    tmp_60_fu_617_p1 = esl_zext<64,10>(tmp_56_fu_612_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_62_fu_1080_p1() {
    tmp_62_fu_1080_p1 = esl_zext<8,3>(grp_fu_461_p4.read());
}

void poly_Sq_frombytes_1::thread_tmp_63_fu_1023_p1() {
    tmp_63_fu_1023_p1 = a_q1.read().range(4-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_64_fu_1092_p3() {
    tmp_64_fu_1092_p3 = esl_concat<3,8>(ap_const_lv3_0, tmp_62_fu_1080_p1.read());
}

void poly_Sq_frombytes_1::thread_tmp_65_fu_1100_p2() {
    tmp_65_fu_1100_p2 = (tmp_64_fu_1092_p3.read() | tmp_44_fu_1084_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_66_fu_1008_p1() {
    tmp_66_fu_1008_p1 = a_q0.read().range(7-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_67_fu_585_p3() {
    tmp_67_fu_585_p3 = esl_concat<3,8>(ap_const_lv3_0, tmp_71_fu_570_p1.read());
}

void poly_Sq_frombytes_1::thread_tmp_68_fu_593_p2() {
    tmp_68_fu_593_p2 = (tmp_67_fu_585_p3.read() | tmp_54_fu_573_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_69_fu_647_p3() {
    tmp_69_fu_647_p3 = esl_concat<7,6>(tmp_92_fu_643_p1.read(), tmp_61_reg_1188.read());
}

void poly_Sq_frombytes_1::thread_tmp_70_fu_1076_p1() {
    tmp_70_fu_1076_p1 = a_q0.read().range(2-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_71_fu_570_p1() {
    tmp_71_fu_570_p1 = esl_zext<8,3>(tmp_53_reg_1173.read());
}

void poly_Sq_frombytes_1::thread_tmp_72_fu_659_p2() {
    tmp_72_fu_659_p2 = (tmp_51_reg_1162.read() | ap_const_lv10_2);
}

void poly_Sq_frombytes_1::thread_tmp_73_fu_664_p1() {
    tmp_73_fu_664_p1 = esl_zext<64,10>(tmp_72_fu_659_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_74_fu_1118_p1() {
    tmp_74_fu_1118_p1 = a_q1.read().range(5-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_75_fu_694_p3() {
    tmp_75_fu_694_p3 = esl_concat<8,1>(a_q1.read(), ap_const_lv1_0);
}

void poly_Sq_frombytes_1::thread_tmp_76_fu_518_p1() {
    tmp_76_fu_518_p1 = a_q1.read().range(5-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_77_fu_706_p3() {
    tmp_77_fu_706_p3 = esl_concat<1,8>(ap_const_lv1_0, tmp_93_fu_691_p1.read());
}

void poly_Sq_frombytes_1::thread_tmp_78_fu_714_p2() {
    tmp_78_fu_714_p2 = (tmp_77_fu_706_p3.read() | tmp_75_fu_694_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_79_fu_720_p3() {
    tmp_79_fu_720_p3 = esl_concat<4,9>(tmp_107_fu_702_p1.read(), tmp_78_fu_714_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_80_fu_733_p2() {
    tmp_80_fu_733_p2 = (tmp_51_reg_1162.read() | ap_const_lv10_3);
}

void poly_Sq_frombytes_1::thread_tmp_81_fu_738_p1() {
    tmp_81_fu_738_p1 = esl_zext<64,10>(tmp_80_fu_733_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_83_cast_fu_607_p1() {
    tmp_83_cast_fu_607_p1 = esl_zext<16,13>(tmp_55_fu_599_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_83_fu_778_p3() {
    tmp_83_fu_778_p3 = esl_concat<8,4>(a_q1.read(), ap_const_lv4_0);
}

void poly_Sq_frombytes_1::thread_tmp_84_fu_581_p1() {
    tmp_84_fu_581_p1 = a_q1.read().range(2-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_85_fu_790_p3() {
    tmp_85_fu_790_p3 = esl_concat<4,8>(ap_const_lv4_0, tmp_94_fu_775_p1.read());
}

void poly_Sq_frombytes_1::thread_tmp_86_fu_798_p2() {
    tmp_86_fu_798_p2 = (tmp_85_fu_790_p3.read() | tmp_83_fu_778_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_87_fu_804_p3() {
    tmp_87_fu_804_p3 = esl_concat<1,12>(tmp_111_fu_786_p1.read(), tmp_86_fu_798_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_88_fu_817_p2() {
    tmp_88_fu_817_p2 = (tmp_51_reg_1162.read() | ap_const_lv10_4);
}

void poly_Sq_frombytes_1::thread_tmp_89_fu_822_p1() {
    tmp_89_fu_822_p1 = esl_zext<64,10>(tmp_88_fu_817_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_91_fu_869_p3() {
    tmp_91_fu_869_p3 = esl_concat<6,7>(tmp_112_fu_865_p1.read(), tmp_90_reg_1228.read());
}

void poly_Sq_frombytes_1::thread_tmp_92_cast_fu_654_p1() {
    tmp_92_cast_fu_654_p1 = esl_zext<16,13>(tmp_69_fu_647_p3.read());
}

void poly_Sq_frombytes_1::thread_tmp_92_fu_643_p1() {
    tmp_92_fu_643_p1 = a_q0.read().range(7-1, 0);
}

void poly_Sq_frombytes_1::thread_tmp_93_fu_691_p1() {
    tmp_93_fu_691_p1 = esl_zext<8,1>(tmp_99_reg_1198.read());
}

void poly_Sq_frombytes_1::thread_tmp_94_fu_775_p1() {
    tmp_94_fu_775_p1 = esl_zext<8,4>(tmp_82_reg_1213.read());
}

void poly_Sq_frombytes_1::thread_tmp_95_fu_881_p2() {
    tmp_95_fu_881_p2 = (tmp_51_reg_1162.read() | ap_const_lv10_5);
}

void poly_Sq_frombytes_1::thread_tmp_96_fu_886_p1() {
    tmp_96_fu_886_p1 = esl_zext<64,10>(tmp_95_fu_881_p2.read());
}

void poly_Sq_frombytes_1::thread_tmp_98_fu_926_p3() {
    tmp_98_fu_926_p3 = esl_concat<8,2>(reg_479.read(), ap_const_lv2_0);
}

void poly_Sq_frombytes_1::thread_tmp_s_fu_490_p2() {
    tmp_s_fu_490_p2 = (!i_reg_437.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_reg_437.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void poly_Sq_frombytes_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_484_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<13>) ("XXXXXXXXXXXXX");
            break;
    }
}

}

