// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "poly_Rq_to_S3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic poly_Rq_to_S3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic poly_Rq_to_S3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state1 = "1";
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state2 = "10";
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state3 = "100";
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state4 = "1000";
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state5 = "10000";
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state6 = "100000";
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> poly_Rq_to_S3::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_1 = "1";
const sc_lv<1> poly_Rq_to_S3::ap_const_lv1_0 = "0";
const sc_lv<1> poly_Rq_to_S3::ap_const_lv1_1 = "1";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_3 = "11";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_5 = "101";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_6 = "110";
const sc_lv<9> poly_Rq_to_S3::ap_const_lv9_0 = "000000000";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_2 = "10";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_4 = "100";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_7 = "111";
const sc_lv<64> poly_Rq_to_S3::ap_const_lv64_1FC = "111111100";
const sc_lv<9> poly_Rq_to_S3::ap_const_lv9_1FD = "111111101";
const sc_lv<9> poly_Rq_to_S3::ap_const_lv9_1 = "1";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_A = "1010";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_E = "1110";
const sc_lv<11> poly_Rq_to_S3::ap_const_lv11_0 = "00000000000";
const sc_lv<16> poly_Rq_to_S3::ap_const_lv16_1800 = "1100000000000";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_8 = "1000";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_F = "1111";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_B = "1011";
const sc_lv<32> poly_Rq_to_S3::ap_const_lv32_9 = "1001";
const sc_lv<3> poly_Rq_to_S3::ap_const_lv3_5 = "101";
const sc_lv<3> poly_Rq_to_S3::ap_const_lv3_7 = "111";
const sc_lv<3> poly_Rq_to_S3::ap_const_lv3_0 = "000";
const sc_lv<16> poly_Rq_to_S3::ap_const_lv16_1 = "1";
const bool poly_Rq_to_S3::ap_const_boolean_1 = true;

poly_Rq_to_S3::poly_Rq_to_S3(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_assign_1_cast_fu_511_p2);
    sensitive << ( tmp_167_fu_461_p3 );
    sensitive << ( tmp_190_fu_469_p1 );

    SC_METHOD(thread_a_assign_1_fu_505_p2);
    sensitive << ( r_coeffs_q0 );
    sensitive << ( tmp_188_fu_451_p2 );

    SC_METHOD(thread_a_coeffs_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_163_p1 );

    SC_METHOD(thread_a_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_fu_434_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_fu_434_p2 );

    SC_METHOD(thread_c_8_cast_fu_701_p3);
    sensitive << ( tmp_195_fu_693_p3 );

    SC_METHOD(thread_c_cast_fu_385_p3);
    sensitive << ( tmp_187_fu_377_p3 );

    SC_METHOD(thread_exitcond1_fu_151_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_129 );

    SC_METHOD(thread_exitcond_fu_434_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_1_reg_140 );

    SC_METHOD(thread_fold1_i9_cast_fu_635_p2);
    sensitive << ( tmp_177_fu_619_p2 );
    sensitive << ( tmp_178_fu_625_p4 );

    SC_METHOD(thread_fold1_i_cast_fu_317_p2);
    sensitive << ( tmp_162_fu_307_p4 );
    sensitive << ( tmp_161_fu_301_p2 );

    SC_METHOD(thread_fold2_i1_cast_fu_673_p2);
    sensitive << ( fold1_i9_cast_reg_803 );
    sensitive << ( tmp_179_reg_809 );

    SC_METHOD(thread_fold2_i_cast_fu_353_p2);
    sensitive << ( fold1_i_cast_fu_317_p2 );
    sensitive << ( tmp_163_fu_343_p4 );

    SC_METHOD(thread_fold_i5_cast_fu_593_p2);
    sensitive << ( tmp_173_fu_561_p2 );
    sensitive << ( tmp_174_fu_567_p4 );

    SC_METHOD(thread_fold_i_cast_fu_275_p2);
    sensitive << ( tmp_185_fu_257_p1 );
    sensitive << ( tmp_fu_247_p4 );

    SC_METHOD(thread_i_8_fu_157_p2);
    sensitive << ( i_reg_129 );

    SC_METHOD(thread_i_9_fu_440_p2);
    sensitive << ( i_1_reg_140 );

    SC_METHOD(thread_not_tmp_53_i1_fu_719_p2);
    sensitive << ( tmp_195_fu_693_p3 );

    SC_METHOD(thread_not_tmp_53_i_fu_403_p2);
    sensitive << ( tmp_187_fu_377_p3 );

    SC_METHOD(thread_r_10_fu_681_p2);
    sensitive << ( tmp_233_i1_cast_fu_669_p1 );
    sensitive << ( tmp_234_i1_cast_fu_677_p1 );

    SC_METHOD(thread_r_4_fu_285_p2);
    sensitive << ( tmp_230_i_cast_fu_281_p1 );
    sensitive << ( tmp_229_i_cast_fu_243_p1 );

    SC_METHOD(thread_r_5_fu_327_p2);
    sensitive << ( tmp_232_i_cast_fu_323_p1 );
    sensitive << ( tmp_231_i_cast_fu_291_p4 );

    SC_METHOD(thread_r_6_fu_365_p2);
    sensitive << ( tmp_234_i_cast_fu_362_p1 );
    sensitive << ( tmp_233_i_cast_fu_359_p1 );

    SC_METHOD(thread_r_7_fu_541_p2);
    sensitive << ( tmp_i1_cast_fu_527_p1 );
    sensitive << ( tmp_i2_cast_fu_531_p1 );

    SC_METHOD(thread_r_8_fu_603_p2);
    sensitive << ( tmp_229_i4_cast_fu_557_p1 );
    sensitive << ( tmp_230_i6_cast_fu_599_p1 );

    SC_METHOD(thread_r_9_fu_654_p2);
    sensitive << ( tmp_231_i8_cast_reg_798 );
    sensitive << ( tmp_232_i1_cast_fu_651_p1 );

    SC_METHOD(thread_r_coeffs_addr_reg_768);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_151_p2 );

    SC_METHOD(thread_r_coeffs_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_reg_758 );
    sensitive << ( r_coeffs_addr_reg_768 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_184_fu_446_p1 );

    SC_METHOD(thread_r_coeffs_address1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( r_coeffs_addr_22_reg_792 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_r_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_r_coeffs_ce1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_r_coeffs_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_183_fu_192_p2 );
    sensitive << ( tmp_238_i_fu_427_p2 );

    SC_METHOD(thread_r_coeffs_d1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_235_i1_cast_fu_715_p1 );
    sensitive << ( tmp_237_i1_cast_fu_739_p1 );

    SC_METHOD(thread_r_coeffs_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_r_coeffs_we1);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_r_fu_227_p2);
    sensitive << ( tmp_i_cast_34_fu_217_p1 );
    sensitive << ( tmp_i_cast_fu_213_p1 );

    SC_METHOD(thread_t_1_fu_687_p2);
    sensitive << ( r_10_fu_681_p2 );

    SC_METHOD(thread_t_fu_371_p2);
    sensitive << ( r_6_fu_365_p2 );

    SC_METHOD(thread_tmp_119_fu_203_p4);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_120_fu_221_p2);
    sensitive << ( tmp_119_fu_203_p4 );
    sensitive << ( tmp_182_fu_199_p1 );

    SC_METHOD(thread_tmp_121_fu_233_p4);
    sensitive << ( r_fu_227_p2 );

    SC_METHOD(thread_tmp_123_fu_168_p4);
    sensitive << ( a_coeffs_q0 );

    SC_METHOD(thread_tmp_128_fu_517_p4);
    sensitive << ( a_assign_1_fu_505_p2 );

    SC_METHOD(thread_tmp_129_fu_535_p2);
    sensitive << ( tmp_128_fu_517_p4 );
    sensitive << ( a_assign_1_cast_fu_511_p2 );

    SC_METHOD(thread_tmp_130_fu_547_p4);
    sensitive << ( r_7_fu_541_p2 );

    SC_METHOD(thread_tmp_131_fu_659_p4);
    sensitive << ( r_9_fu_654_p2 );

    SC_METHOD(thread_tmp_160_fu_265_p4);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_161_fu_301_p2);
    sensitive << ( tmp_186_fu_261_p1 );
    sensitive << ( tmp_160_fu_265_p4 );

    SC_METHOD(thread_tmp_162_fu_307_p4);
    sensitive << ( tmp_120_fu_221_p2 );

    SC_METHOD(thread_tmp_163_fu_343_p4);
    sensitive << ( r_4_fu_285_p2 );

    SC_METHOD(thread_tmp_167_fu_461_p3);
    sensitive << ( tmp_189_fu_457_p1 );

    SC_METHOD(thread_tmp_170_fu_481_p3);
    sensitive << ( tmp_192_fu_477_p1 );

    SC_METHOD(thread_tmp_171_fu_493_p3);
    sensitive << ( tmp_193_fu_489_p1 );

    SC_METHOD(thread_tmp_173_fu_561_p2);
    sensitive << ( tmp_170_fu_481_p3 );
    sensitive << ( tmp_191_fu_473_p1 );

    SC_METHOD(thread_tmp_174_fu_567_p4);
    sensitive << ( a_assign_1_fu_505_p2 );

    SC_METHOD(thread_tmp_175_fu_577_p4);
    sensitive << ( a_assign_1_fu_505_p2 );

    SC_METHOD(thread_tmp_176_fu_587_p2);
    sensitive << ( tmp_171_fu_493_p3 );
    sensitive << ( tmp_194_fu_501_p1 );

    SC_METHOD(thread_tmp_177_fu_619_p2);
    sensitive << ( tmp_176_fu_587_p2 );
    sensitive << ( tmp_175_fu_577_p4 );

    SC_METHOD(thread_tmp_178_fu_625_p4);
    sensitive << ( tmp_129_fu_535_p2 );

    SC_METHOD(thread_tmp_180_fu_178_p3);
    sensitive << ( tmp_123_fu_168_p4 );

    SC_METHOD(thread_tmp_181_fu_186_p2);
    sensitive << ( tmp_180_fu_178_p3 );

    SC_METHOD(thread_tmp_182_fu_199_p1);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_183_fu_192_p2);
    sensitive << ( a_coeffs_q0 );
    sensitive << ( tmp_181_fu_186_p2 );

    SC_METHOD(thread_tmp_184_fu_446_p1);
    sensitive << ( i_1_reg_140 );

    SC_METHOD(thread_tmp_185_fu_257_p1);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_186_fu_261_p1);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_187_fu_377_p3);
    sensitive << ( t_fu_371_p2 );

    SC_METHOD(thread_tmp_188_fu_451_p2);
    sensitive << ( r_coeffs_q1 );

    SC_METHOD(thread_tmp_189_fu_457_p1);
    sensitive << ( r_coeffs_q1 );

    SC_METHOD(thread_tmp_190_fu_469_p1);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_191_fu_473_p1);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_192_fu_477_p1);
    sensitive << ( r_coeffs_q1 );

    SC_METHOD(thread_tmp_193_fu_489_p1);
    sensitive << ( r_coeffs_q1 );

    SC_METHOD(thread_tmp_194_fu_501_p1);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_195_fu_693_p3);
    sensitive << ( t_1_fu_687_p2 );

    SC_METHOD(thread_tmp_229_i4_cast_fu_557_p1);
    sensitive << ( tmp_130_fu_547_p4 );

    SC_METHOD(thread_tmp_229_i_cast_fu_243_p1);
    sensitive << ( tmp_121_fu_233_p4 );

    SC_METHOD(thread_tmp_230_i6_cast_fu_599_p1);
    sensitive << ( fold_i5_cast_fu_593_p2 );

    SC_METHOD(thread_tmp_230_i_cast_fu_281_p1);
    sensitive << ( fold_i_cast_fu_275_p2 );

    SC_METHOD(thread_tmp_231_i_cast_fu_291_p4);
    sensitive << ( r_4_fu_285_p2 );

    SC_METHOD(thread_tmp_232_i1_cast_fu_651_p1);
    sensitive << ( fold1_i9_cast_reg_803 );

    SC_METHOD(thread_tmp_232_i_cast_fu_323_p1);
    sensitive << ( fold1_i_cast_fu_317_p2 );

    SC_METHOD(thread_tmp_233_i1_cast_fu_669_p1);
    sensitive << ( tmp_131_fu_659_p4 );

    SC_METHOD(thread_tmp_233_i_cast_fu_359_p1);
    sensitive << ( tmp_122_reg_774 );

    SC_METHOD(thread_tmp_234_i1_cast_fu_677_p1);
    sensitive << ( fold2_i1_cast_fu_673_p2 );

    SC_METHOD(thread_tmp_234_i_cast_fu_362_p1);
    sensitive << ( fold2_i_cast_reg_779 );

    SC_METHOD(thread_tmp_235_i1_cast_fu_715_p1);
    sensitive << ( tmp_235_i1_fu_709_p2 );

    SC_METHOD(thread_tmp_235_i1_fu_709_p2);
    sensitive << ( r_10_fu_681_p2 );
    sensitive << ( c_8_cast_fu_701_p3 );

    SC_METHOD(thread_tmp_235_i_cast_fu_399_p1);
    sensitive << ( tmp_235_i_fu_393_p2 );

    SC_METHOD(thread_tmp_235_i_fu_393_p2);
    sensitive << ( r_6_fu_365_p2 );
    sensitive << ( c_cast_fu_385_p3 );

    SC_METHOD(thread_tmp_236_i1_cast_cast_fu_725_p3);
    sensitive << ( not_tmp_53_i1_fu_719_p2 );

    SC_METHOD(thread_tmp_236_i_cast_cast_fu_409_p3);
    sensitive << ( not_tmp_53_i_fu_403_p2 );

    SC_METHOD(thread_tmp_237_i1_cast_fu_739_p1);
    sensitive << ( tmp_237_i1_fu_733_p2 );

    SC_METHOD(thread_tmp_237_i1_fu_733_p2);
    sensitive << ( t_1_fu_687_p2 );
    sensitive << ( tmp_236_i1_cast_cast_fu_725_p3 );

    SC_METHOD(thread_tmp_237_i_cast_fu_423_p1);
    sensitive << ( tmp_237_i_fu_417_p2 );

    SC_METHOD(thread_tmp_237_i_fu_417_p2);
    sensitive << ( t_fu_371_p2 );
    sensitive << ( tmp_236_i_cast_cast_fu_409_p3 );

    SC_METHOD(thread_tmp_238_i_fu_427_p2);
    sensitive << ( tmp_235_i_cast_fu_399_p1 );
    sensitive << ( tmp_237_i_cast_fu_423_p1 );

    SC_METHOD(thread_tmp_fu_247_p4);
    sensitive << ( r_coeffs_q0 );

    SC_METHOD(thread_tmp_i1_cast_fu_527_p1);
    sensitive << ( tmp_128_fu_517_p4 );

    SC_METHOD(thread_tmp_i2_cast_fu_531_p1);
    sensitive << ( a_assign_1_cast_fu_511_p2 );

    SC_METHOD(thread_tmp_i_cast_34_fu_217_p1);
    sensitive << ( tmp_182_fu_199_p1 );

    SC_METHOD(thread_tmp_i_cast_fu_213_p1);
    sensitive << ( tmp_119_fu_203_p4 );

    SC_METHOD(thread_tmp_s_fu_163_p1);
    sensitive << ( i_reg_129 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_151_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_fu_434_p2 );

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "poly_Rq_to_S3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, r_coeffs_address0, "(port)r_coeffs_address0");
    sc_trace(mVcdFile, r_coeffs_ce0, "(port)r_coeffs_ce0");
    sc_trace(mVcdFile, r_coeffs_we0, "(port)r_coeffs_we0");
    sc_trace(mVcdFile, r_coeffs_d0, "(port)r_coeffs_d0");
    sc_trace(mVcdFile, r_coeffs_q0, "(port)r_coeffs_q0");
    sc_trace(mVcdFile, r_coeffs_address1, "(port)r_coeffs_address1");
    sc_trace(mVcdFile, r_coeffs_ce1, "(port)r_coeffs_ce1");
    sc_trace(mVcdFile, r_coeffs_we1, "(port)r_coeffs_we1");
    sc_trace(mVcdFile, r_coeffs_d1, "(port)r_coeffs_d1");
    sc_trace(mVcdFile, r_coeffs_q1, "(port)r_coeffs_q1");
    sc_trace(mVcdFile, a_coeffs_address0, "(port)a_coeffs_address0");
    sc_trace(mVcdFile, a_coeffs_ce0, "(port)a_coeffs_ce0");
    sc_trace(mVcdFile, a_coeffs_q0, "(port)a_coeffs_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_8_fu_157_p2, "i_8_fu_157_p2");
    sc_trace(mVcdFile, i_8_reg_753, "i_8_reg_753");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_s_fu_163_p1, "tmp_s_fu_163_p1");
    sc_trace(mVcdFile, tmp_s_reg_758, "tmp_s_reg_758");
    sc_trace(mVcdFile, exitcond1_fu_151_p2, "exitcond1_fu_151_p2");
    sc_trace(mVcdFile, r_coeffs_addr_reg_768, "r_coeffs_addr_reg_768");
    sc_trace(mVcdFile, tmp_122_reg_774, "tmp_122_reg_774");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, fold2_i_cast_fu_353_p2, "fold2_i_cast_fu_353_p2");
    sc_trace(mVcdFile, fold2_i_cast_reg_779, "fold2_i_cast_reg_779");
    sc_trace(mVcdFile, i_9_fu_440_p2, "i_9_fu_440_p2");
    sc_trace(mVcdFile, i_9_reg_787, "i_9_reg_787");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, r_coeffs_addr_22_reg_792, "r_coeffs_addr_22_reg_792");
    sc_trace(mVcdFile, exitcond_fu_434_p2, "exitcond_fu_434_p2");
    sc_trace(mVcdFile, tmp_231_i8_cast_reg_798, "tmp_231_i8_cast_reg_798");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, fold1_i9_cast_fu_635_p2, "fold1_i9_cast_fu_635_p2");
    sc_trace(mVcdFile, fold1_i9_cast_reg_803, "fold1_i9_cast_reg_803");
    sc_trace(mVcdFile, tmp_179_reg_809, "tmp_179_reg_809");
    sc_trace(mVcdFile, i_reg_129, "i_reg_129");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_1_reg_140, "i_1_reg_140");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_184_fu_446_p1, "tmp_184_fu_446_p1");
    sc_trace(mVcdFile, tmp_183_fu_192_p2, "tmp_183_fu_192_p2");
    sc_trace(mVcdFile, tmp_238_i_fu_427_p2, "tmp_238_i_fu_427_p2");
    sc_trace(mVcdFile, tmp_123_fu_168_p4, "tmp_123_fu_168_p4");
    sc_trace(mVcdFile, tmp_180_fu_178_p3, "tmp_180_fu_178_p3");
    sc_trace(mVcdFile, tmp_181_fu_186_p2, "tmp_181_fu_186_p2");
    sc_trace(mVcdFile, tmp_119_fu_203_p4, "tmp_119_fu_203_p4");
    sc_trace(mVcdFile, tmp_182_fu_199_p1, "tmp_182_fu_199_p1");
    sc_trace(mVcdFile, tmp_i_cast_34_fu_217_p1, "tmp_i_cast_34_fu_217_p1");
    sc_trace(mVcdFile, tmp_i_cast_fu_213_p1, "tmp_i_cast_fu_213_p1");
    sc_trace(mVcdFile, r_fu_227_p2, "r_fu_227_p2");
    sc_trace(mVcdFile, tmp_121_fu_233_p4, "tmp_121_fu_233_p4");
    sc_trace(mVcdFile, tmp_185_fu_257_p1, "tmp_185_fu_257_p1");
    sc_trace(mVcdFile, tmp_fu_247_p4, "tmp_fu_247_p4");
    sc_trace(mVcdFile, fold_i_cast_fu_275_p2, "fold_i_cast_fu_275_p2");
    sc_trace(mVcdFile, tmp_230_i_cast_fu_281_p1, "tmp_230_i_cast_fu_281_p1");
    sc_trace(mVcdFile, tmp_229_i_cast_fu_243_p1, "tmp_229_i_cast_fu_243_p1");
    sc_trace(mVcdFile, r_4_fu_285_p2, "r_4_fu_285_p2");
    sc_trace(mVcdFile, tmp_186_fu_261_p1, "tmp_186_fu_261_p1");
    sc_trace(mVcdFile, tmp_160_fu_265_p4, "tmp_160_fu_265_p4");
    sc_trace(mVcdFile, tmp_120_fu_221_p2, "tmp_120_fu_221_p2");
    sc_trace(mVcdFile, tmp_162_fu_307_p4, "tmp_162_fu_307_p4");
    sc_trace(mVcdFile, tmp_161_fu_301_p2, "tmp_161_fu_301_p2");
    sc_trace(mVcdFile, fold1_i_cast_fu_317_p2, "fold1_i_cast_fu_317_p2");
    sc_trace(mVcdFile, tmp_232_i_cast_fu_323_p1, "tmp_232_i_cast_fu_323_p1");
    sc_trace(mVcdFile, tmp_231_i_cast_fu_291_p4, "tmp_231_i_cast_fu_291_p4");
    sc_trace(mVcdFile, r_5_fu_327_p2, "r_5_fu_327_p2");
    sc_trace(mVcdFile, tmp_163_fu_343_p4, "tmp_163_fu_343_p4");
    sc_trace(mVcdFile, tmp_234_i_cast_fu_362_p1, "tmp_234_i_cast_fu_362_p1");
    sc_trace(mVcdFile, tmp_233_i_cast_fu_359_p1, "tmp_233_i_cast_fu_359_p1");
    sc_trace(mVcdFile, r_6_fu_365_p2, "r_6_fu_365_p2");
    sc_trace(mVcdFile, t_fu_371_p2, "t_fu_371_p2");
    sc_trace(mVcdFile, tmp_187_fu_377_p3, "tmp_187_fu_377_p3");
    sc_trace(mVcdFile, c_cast_fu_385_p3, "c_cast_fu_385_p3");
    sc_trace(mVcdFile, tmp_235_i_fu_393_p2, "tmp_235_i_fu_393_p2");
    sc_trace(mVcdFile, not_tmp_53_i_fu_403_p2, "not_tmp_53_i_fu_403_p2");
    sc_trace(mVcdFile, tmp_236_i_cast_cast_fu_409_p3, "tmp_236_i_cast_cast_fu_409_p3");
    sc_trace(mVcdFile, tmp_237_i_fu_417_p2, "tmp_237_i_fu_417_p2");
    sc_trace(mVcdFile, tmp_235_i_cast_fu_399_p1, "tmp_235_i_cast_fu_399_p1");
    sc_trace(mVcdFile, tmp_237_i_cast_fu_423_p1, "tmp_237_i_cast_fu_423_p1");
    sc_trace(mVcdFile, tmp_189_fu_457_p1, "tmp_189_fu_457_p1");
    sc_trace(mVcdFile, tmp_192_fu_477_p1, "tmp_192_fu_477_p1");
    sc_trace(mVcdFile, tmp_193_fu_489_p1, "tmp_193_fu_489_p1");
    sc_trace(mVcdFile, tmp_188_fu_451_p2, "tmp_188_fu_451_p2");
    sc_trace(mVcdFile, tmp_167_fu_461_p3, "tmp_167_fu_461_p3");
    sc_trace(mVcdFile, tmp_190_fu_469_p1, "tmp_190_fu_469_p1");
    sc_trace(mVcdFile, a_assign_1_fu_505_p2, "a_assign_1_fu_505_p2");
    sc_trace(mVcdFile, tmp_128_fu_517_p4, "tmp_128_fu_517_p4");
    sc_trace(mVcdFile, a_assign_1_cast_fu_511_p2, "a_assign_1_cast_fu_511_p2");
    sc_trace(mVcdFile, tmp_i1_cast_fu_527_p1, "tmp_i1_cast_fu_527_p1");
    sc_trace(mVcdFile, tmp_i2_cast_fu_531_p1, "tmp_i2_cast_fu_531_p1");
    sc_trace(mVcdFile, r_7_fu_541_p2, "r_7_fu_541_p2");
    sc_trace(mVcdFile, tmp_130_fu_547_p4, "tmp_130_fu_547_p4");
    sc_trace(mVcdFile, tmp_170_fu_481_p3, "tmp_170_fu_481_p3");
    sc_trace(mVcdFile, tmp_191_fu_473_p1, "tmp_191_fu_473_p1");
    sc_trace(mVcdFile, tmp_171_fu_493_p3, "tmp_171_fu_493_p3");
    sc_trace(mVcdFile, tmp_194_fu_501_p1, "tmp_194_fu_501_p1");
    sc_trace(mVcdFile, tmp_173_fu_561_p2, "tmp_173_fu_561_p2");
    sc_trace(mVcdFile, tmp_174_fu_567_p4, "tmp_174_fu_567_p4");
    sc_trace(mVcdFile, fold_i5_cast_fu_593_p2, "fold_i5_cast_fu_593_p2");
    sc_trace(mVcdFile, tmp_229_i4_cast_fu_557_p1, "tmp_229_i4_cast_fu_557_p1");
    sc_trace(mVcdFile, tmp_230_i6_cast_fu_599_p1, "tmp_230_i6_cast_fu_599_p1");
    sc_trace(mVcdFile, r_8_fu_603_p2, "r_8_fu_603_p2");
    sc_trace(mVcdFile, tmp_176_fu_587_p2, "tmp_176_fu_587_p2");
    sc_trace(mVcdFile, tmp_175_fu_577_p4, "tmp_175_fu_577_p4");
    sc_trace(mVcdFile, tmp_129_fu_535_p2, "tmp_129_fu_535_p2");
    sc_trace(mVcdFile, tmp_177_fu_619_p2, "tmp_177_fu_619_p2");
    sc_trace(mVcdFile, tmp_178_fu_625_p4, "tmp_178_fu_625_p4");
    sc_trace(mVcdFile, tmp_232_i1_cast_fu_651_p1, "tmp_232_i1_cast_fu_651_p1");
    sc_trace(mVcdFile, r_9_fu_654_p2, "r_9_fu_654_p2");
    sc_trace(mVcdFile, tmp_131_fu_659_p4, "tmp_131_fu_659_p4");
    sc_trace(mVcdFile, fold2_i1_cast_fu_673_p2, "fold2_i1_cast_fu_673_p2");
    sc_trace(mVcdFile, tmp_233_i1_cast_fu_669_p1, "tmp_233_i1_cast_fu_669_p1");
    sc_trace(mVcdFile, tmp_234_i1_cast_fu_677_p1, "tmp_234_i1_cast_fu_677_p1");
    sc_trace(mVcdFile, r_10_fu_681_p2, "r_10_fu_681_p2");
    sc_trace(mVcdFile, t_1_fu_687_p2, "t_1_fu_687_p2");
    sc_trace(mVcdFile, tmp_195_fu_693_p3, "tmp_195_fu_693_p3");
    sc_trace(mVcdFile, c_8_cast_fu_701_p3, "c_8_cast_fu_701_p3");
    sc_trace(mVcdFile, tmp_235_i1_fu_709_p2, "tmp_235_i1_fu_709_p2");
    sc_trace(mVcdFile, not_tmp_53_i1_fu_719_p2, "not_tmp_53_i1_fu_719_p2");
    sc_trace(mVcdFile, tmp_236_i1_cast_cast_fu_725_p3, "tmp_236_i1_cast_cast_fu_725_p3");
    sc_trace(mVcdFile, tmp_237_i1_fu_733_p2, "tmp_237_i1_fu_733_p2");
    sc_trace(mVcdFile, tmp_235_i1_cast_fu_715_p1, "tmp_235_i1_cast_fu_715_p1");
    sc_trace(mVcdFile, tmp_237_i1_cast_fu_739_p1, "tmp_237_i1_cast_fu_739_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

poly_Rq_to_S3::~poly_Rq_to_S3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void poly_Rq_to_S3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_1_reg_140 = i_9_reg_787.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_1_reg_140 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_129 = i_8_reg_753.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_129 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        fold1_i9_cast_reg_803 = fold1_i9_cast_fu_635_p2.read();
        tmp_179_reg_809 = r_8_fu_603_p2.read().range(3, 2);
        tmp_231_i8_cast_reg_798 = r_8_fu_603_p2.read().range(5, 2);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        fold2_i_cast_reg_779 = fold2_i_cast_fu_353_p2.read();
        tmp_122_reg_774 = r_5_fu_327_p2.read().range(3, 2);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_8_reg_753 = i_8_fu_157_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_9_reg_787 = i_9_fu_440_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_434_p2.read()))) {
        r_coeffs_addr_22_reg_792 =  (sc_lv<9>) (tmp_184_fu_446_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_151_p2.read(), ap_const_lv1_0))) {
        tmp_s_reg_758 = tmp_s_fu_163_p1.read();
    }
}

void poly_Rq_to_S3::thread_a_assign_1_cast_fu_511_p2() {
    a_assign_1_cast_fu_511_p2 = (!tmp_167_fu_461_p3.read().is_01() || !tmp_190_fu_469_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_167_fu_461_p3.read()) + sc_biguint<8>(tmp_190_fu_469_p1.read()));
}

void poly_Rq_to_S3::thread_a_assign_1_fu_505_p2() {
    a_assign_1_fu_505_p2 = (!r_coeffs_q0.read().is_01() || !tmp_188_fu_451_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(r_coeffs_q0.read()) + sc_biguint<16>(tmp_188_fu_451_p2.read()));
}

void poly_Rq_to_S3::thread_a_coeffs_address0() {
    a_coeffs_address0 =  (sc_lv<9>) (tmp_s_fu_163_p1.read());
}

void poly_Rq_to_S3::thread_a_coeffs_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        a_coeffs_ce0 = ap_const_logic_1;
    } else {
        a_coeffs_ce0 = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void poly_Rq_to_S3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void poly_Rq_to_S3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_434_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_434_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_c_8_cast_fu_701_p3() {
    c_8_cast_fu_701_p3 = (!tmp_195_fu_693_p3.read()[0].is_01())? sc_lv<3>(): ((tmp_195_fu_693_p3.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_0);
}

void poly_Rq_to_S3::thread_c_cast_fu_385_p3() {
    c_cast_fu_385_p3 = (!tmp_187_fu_377_p3.read()[0].is_01())? sc_lv<3>(): ((tmp_187_fu_377_p3.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_0);
}

void poly_Rq_to_S3::thread_exitcond1_fu_151_p2() {
    exitcond1_fu_151_p2 = (!i_reg_129.read().is_01() || !ap_const_lv9_1FD.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_129.read() == ap_const_lv9_1FD);
}

void poly_Rq_to_S3::thread_exitcond_fu_434_p2() {
    exitcond_fu_434_p2 = (!i_1_reg_140.read().is_01() || !ap_const_lv9_1FD.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_140.read() == ap_const_lv9_1FD);
}

void poly_Rq_to_S3::thread_fold1_i9_cast_fu_635_p2() {
    fold1_i9_cast_fu_635_p2 = (!tmp_177_fu_619_p2.read().is_01() || !tmp_178_fu_625_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_177_fu_619_p2.read()) + sc_biguint<2>(tmp_178_fu_625_p4.read()));
}

void poly_Rq_to_S3::thread_fold1_i_cast_fu_317_p2() {
    fold1_i_cast_fu_317_p2 = (!tmp_162_fu_307_p4.read().is_01() || !tmp_161_fu_301_p2.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_162_fu_307_p4.read()) + sc_biguint<2>(tmp_161_fu_301_p2.read()));
}

void poly_Rq_to_S3::thread_fold2_i1_cast_fu_673_p2() {
    fold2_i1_cast_fu_673_p2 = (!tmp_179_reg_809.read().is_01() || !fold1_i9_cast_reg_803.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_179_reg_809.read()) + sc_biguint<2>(fold1_i9_cast_reg_803.read()));
}

void poly_Rq_to_S3::thread_fold2_i_cast_fu_353_p2() {
    fold2_i_cast_fu_353_p2 = (!fold1_i_cast_fu_317_p2.read().is_01() || !tmp_163_fu_343_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(fold1_i_cast_fu_317_p2.read()) + sc_biguint<2>(tmp_163_fu_343_p4.read()));
}

void poly_Rq_to_S3::thread_fold_i5_cast_fu_593_p2() {
    fold_i5_cast_fu_593_p2 = (!tmp_173_fu_561_p2.read().is_01() || !tmp_174_fu_567_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_173_fu_561_p2.read()) + sc_biguint<4>(tmp_174_fu_567_p4.read()));
}

void poly_Rq_to_S3::thread_fold_i_cast_fu_275_p2() {
    fold_i_cast_fu_275_p2 = (!tmp_185_fu_257_p1.read().is_01() || !tmp_fu_247_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_185_fu_257_p1.read()) + sc_biguint<4>(tmp_fu_247_p4.read()));
}

void poly_Rq_to_S3::thread_i_8_fu_157_p2() {
    i_8_fu_157_p2 = (!i_reg_129.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_129.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void poly_Rq_to_S3::thread_i_9_fu_440_p2() {
    i_9_fu_440_p2 = (!i_1_reg_140.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_1_reg_140.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void poly_Rq_to_S3::thread_not_tmp_53_i1_fu_719_p2() {
    not_tmp_53_i1_fu_719_p2 = (tmp_195_fu_693_p3.read() ^ ap_const_lv1_1);
}

void poly_Rq_to_S3::thread_not_tmp_53_i_fu_403_p2() {
    not_tmp_53_i_fu_403_p2 = (tmp_187_fu_377_p3.read() ^ ap_const_lv1_1);
}

void poly_Rq_to_S3::thread_r_10_fu_681_p2() {
    r_10_fu_681_p2 = (!tmp_233_i1_cast_fu_669_p1.read().is_01() || !tmp_234_i1_cast_fu_677_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp_233_i1_cast_fu_669_p1.read()) + sc_biguint<3>(tmp_234_i1_cast_fu_677_p1.read()));
}

void poly_Rq_to_S3::thread_r_4_fu_285_p2() {
    r_4_fu_285_p2 = (!tmp_230_i_cast_fu_281_p1.read().is_01() || !tmp_229_i_cast_fu_243_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_230_i_cast_fu_281_p1.read()) + sc_biguint<6>(tmp_229_i_cast_fu_243_p1.read()));
}

void poly_Rq_to_S3::thread_r_5_fu_327_p2() {
    r_5_fu_327_p2 = (!tmp_232_i_cast_fu_323_p1.read().is_01() || !tmp_231_i_cast_fu_291_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_232_i_cast_fu_323_p1.read()) + sc_biguint<4>(tmp_231_i_cast_fu_291_p4.read()));
}

void poly_Rq_to_S3::thread_r_6_fu_365_p2() {
    r_6_fu_365_p2 = (!tmp_234_i_cast_fu_362_p1.read().is_01() || !tmp_233_i_cast_fu_359_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(tmp_234_i_cast_fu_362_p1.read()) + sc_biguint<3>(tmp_233_i_cast_fu_359_p1.read()));
}

void poly_Rq_to_S3::thread_r_7_fu_541_p2() {
    r_7_fu_541_p2 = (!tmp_i1_cast_fu_527_p1.read().is_01() || !tmp_i2_cast_fu_531_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_i1_cast_fu_527_p1.read()) + sc_biguint<9>(tmp_i2_cast_fu_531_p1.read()));
}

void poly_Rq_to_S3::thread_r_8_fu_603_p2() {
    r_8_fu_603_p2 = (!tmp_229_i4_cast_fu_557_p1.read().is_01() || !tmp_230_i6_cast_fu_599_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_229_i4_cast_fu_557_p1.read()) + sc_biguint<6>(tmp_230_i6_cast_fu_599_p1.read()));
}

void poly_Rq_to_S3::thread_r_9_fu_654_p2() {
    r_9_fu_654_p2 = (!tmp_231_i8_cast_reg_798.read().is_01() || !tmp_232_i1_cast_fu_651_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_231_i8_cast_reg_798.read()) + sc_biguint<4>(tmp_232_i1_cast_fu_651_p1.read()));
}

void poly_Rq_to_S3::thread_r_coeffs_addr_reg_768() {
    r_coeffs_addr_reg_768 =  (sc_lv<9>) (ap_const_lv64_1FC);
}

void poly_Rq_to_S3::thread_r_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        r_coeffs_address0 =  (sc_lv<9>) (tmp_184_fu_446_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        r_coeffs_address0 = r_coeffs_addr_reg_768.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        r_coeffs_address0 =  (sc_lv<9>) (tmp_s_reg_758.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        r_coeffs_address0 =  (sc_lv<9>) (ap_const_lv64_1FC);
    } else {
        r_coeffs_address0 = "XXXXXXXXX";
    }
}

void poly_Rq_to_S3::thread_r_coeffs_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        r_coeffs_address1 = r_coeffs_addr_22_reg_792.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        r_coeffs_address1 =  (sc_lv<9>) (ap_const_lv64_1FC);
    } else {
        r_coeffs_address1 = "XXXXXXXXX";
    }
}

void poly_Rq_to_S3::thread_r_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        r_coeffs_ce0 = ap_const_logic_1;
    } else {
        r_coeffs_ce0 = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_r_coeffs_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        r_coeffs_ce1 = ap_const_logic_1;
    } else {
        r_coeffs_ce1 = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_r_coeffs_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        r_coeffs_d0 = tmp_238_i_fu_427_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        r_coeffs_d0 = tmp_183_fu_192_p2.read();
    } else {
        r_coeffs_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void poly_Rq_to_S3::thread_r_coeffs_d1() {
    r_coeffs_d1 = (tmp_235_i1_cast_fu_715_p1.read() ^ tmp_237_i1_cast_fu_739_p1.read());
}

void poly_Rq_to_S3::thread_r_coeffs_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        r_coeffs_we0 = ap_const_logic_1;
    } else {
        r_coeffs_we0 = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_r_coeffs_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        r_coeffs_we1 = ap_const_logic_1;
    } else {
        r_coeffs_we1 = ap_const_logic_0;
    }
}

void poly_Rq_to_S3::thread_r_fu_227_p2() {
    r_fu_227_p2 = (!tmp_i_cast_34_fu_217_p1.read().is_01() || !tmp_i_cast_fu_213_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_i_cast_34_fu_217_p1.read()) + sc_biguint<9>(tmp_i_cast_fu_213_p1.read()));
}

void poly_Rq_to_S3::thread_t_1_fu_687_p2() {
    t_1_fu_687_p2 = (!ap_const_lv3_5.is_01() || !r_10_fu_681_p2.read().is_01())? sc_lv<3>(): (sc_bigint<3>(ap_const_lv3_5) + sc_biguint<3>(r_10_fu_681_p2.read()));
}

void poly_Rq_to_S3::thread_t_fu_371_p2() {
    t_fu_371_p2 = (!ap_const_lv3_5.is_01() || !r_6_fu_365_p2.read().is_01())? sc_lv<3>(): (sc_bigint<3>(ap_const_lv3_5) + sc_biguint<3>(r_6_fu_365_p2.read()));
}

void poly_Rq_to_S3::thread_tmp_119_fu_203_p4() {
    tmp_119_fu_203_p4 = r_coeffs_q0.read().range(15, 8);
}

void poly_Rq_to_S3::thread_tmp_120_fu_221_p2() {
    tmp_120_fu_221_p2 = (!tmp_119_fu_203_p4.read().is_01() || !tmp_182_fu_199_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_119_fu_203_p4.read()) + sc_biguint<8>(tmp_182_fu_199_p1.read()));
}

void poly_Rq_to_S3::thread_tmp_121_fu_233_p4() {
    tmp_121_fu_233_p4 = r_fu_227_p2.read().range(8, 4);
}

void poly_Rq_to_S3::thread_tmp_123_fu_168_p4() {
    tmp_123_fu_168_p4 = a_coeffs_q0.read().range(14, 10);
}

void poly_Rq_to_S3::thread_tmp_128_fu_517_p4() {
    tmp_128_fu_517_p4 = a_assign_1_fu_505_p2.read().range(15, 8);
}

void poly_Rq_to_S3::thread_tmp_129_fu_535_p2() {
    tmp_129_fu_535_p2 = (!a_assign_1_cast_fu_511_p2.read().is_01() || !tmp_128_fu_517_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(a_assign_1_cast_fu_511_p2.read()) + sc_biguint<8>(tmp_128_fu_517_p4.read()));
}

void poly_Rq_to_S3::thread_tmp_130_fu_547_p4() {
    tmp_130_fu_547_p4 = r_7_fu_541_p2.read().range(8, 4);
}

void poly_Rq_to_S3::thread_tmp_131_fu_659_p4() {
    tmp_131_fu_659_p4 = r_9_fu_654_p2.read().range(3, 2);
}

void poly_Rq_to_S3::thread_tmp_160_fu_265_p4() {
    tmp_160_fu_265_p4 = r_coeffs_q0.read().range(9, 8);
}

void poly_Rq_to_S3::thread_tmp_161_fu_301_p2() {
    tmp_161_fu_301_p2 = (!tmp_186_fu_261_p1.read().is_01() || !tmp_160_fu_265_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_186_fu_261_p1.read()) + sc_biguint<2>(tmp_160_fu_265_p4.read()));
}

void poly_Rq_to_S3::thread_tmp_162_fu_307_p4() {
    tmp_162_fu_307_p4 = tmp_120_fu_221_p2.read().range(5, 4);
}

void poly_Rq_to_S3::thread_tmp_163_fu_343_p4() {
    tmp_163_fu_343_p4 = r_4_fu_285_p2.read().range(3, 2);
}

void poly_Rq_to_S3::thread_tmp_167_fu_461_p3() {
    tmp_167_fu_461_p3 = esl_concat<7,1>(tmp_189_fu_457_p1.read(), ap_const_lv1_0);
}

void poly_Rq_to_S3::thread_tmp_170_fu_481_p3() {
    tmp_170_fu_481_p3 = esl_concat<3,1>(tmp_192_fu_477_p1.read(), ap_const_lv1_0);
}

void poly_Rq_to_S3::thread_tmp_171_fu_493_p3() {
    tmp_171_fu_493_p3 = esl_concat<1,1>(tmp_193_fu_489_p1.read(), ap_const_lv1_0);
}

void poly_Rq_to_S3::thread_tmp_173_fu_561_p2() {
    tmp_173_fu_561_p2 = (!tmp_170_fu_481_p3.read().is_01() || !tmp_191_fu_473_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_170_fu_481_p3.read()) + sc_biguint<4>(tmp_191_fu_473_p1.read()));
}

void poly_Rq_to_S3::thread_tmp_174_fu_567_p4() {
    tmp_174_fu_567_p4 = a_assign_1_fu_505_p2.read().range(11, 8);
}

void poly_Rq_to_S3::thread_tmp_175_fu_577_p4() {
    tmp_175_fu_577_p4 = a_assign_1_fu_505_p2.read().range(9, 8);
}

void poly_Rq_to_S3::thread_tmp_176_fu_587_p2() {
    tmp_176_fu_587_p2 = (!tmp_171_fu_493_p3.read().is_01() || !tmp_194_fu_501_p1.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_171_fu_493_p3.read()) + sc_biguint<2>(tmp_194_fu_501_p1.read()));
}

void poly_Rq_to_S3::thread_tmp_177_fu_619_p2() {
    tmp_177_fu_619_p2 = (!tmp_176_fu_587_p2.read().is_01() || !tmp_175_fu_577_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_176_fu_587_p2.read()) + sc_biguint<2>(tmp_175_fu_577_p4.read()));
}

void poly_Rq_to_S3::thread_tmp_178_fu_625_p4() {
    tmp_178_fu_625_p4 = tmp_129_fu_535_p2.read().range(5, 4);
}

void poly_Rq_to_S3::thread_tmp_180_fu_178_p3() {
    tmp_180_fu_178_p3 = esl_concat<5,11>(tmp_123_fu_168_p4.read(), ap_const_lv11_0);
}

void poly_Rq_to_S3::thread_tmp_181_fu_186_p2() {
    tmp_181_fu_186_p2 = (tmp_180_fu_178_p3.read() ^ ap_const_lv16_1800);
}

void poly_Rq_to_S3::thread_tmp_182_fu_199_p1() {
    tmp_182_fu_199_p1 = r_coeffs_q0.read().range(8-1, 0);
}

void poly_Rq_to_S3::thread_tmp_183_fu_192_p2() {
    tmp_183_fu_192_p2 = (!tmp_181_fu_186_p2.read().is_01() || !a_coeffs_q0.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_181_fu_186_p2.read()) + sc_biguint<16>(a_coeffs_q0.read()));
}

void poly_Rq_to_S3::thread_tmp_184_fu_446_p1() {
    tmp_184_fu_446_p1 = esl_zext<64,9>(i_1_reg_140.read());
}

void poly_Rq_to_S3::thread_tmp_185_fu_257_p1() {
    tmp_185_fu_257_p1 = r_coeffs_q0.read().range(4-1, 0);
}

void poly_Rq_to_S3::thread_tmp_186_fu_261_p1() {
    tmp_186_fu_261_p1 = r_coeffs_q0.read().range(2-1, 0);
}

void poly_Rq_to_S3::thread_tmp_187_fu_377_p3() {
    tmp_187_fu_377_p3 = t_fu_371_p2.read().range(2, 2);
}

void poly_Rq_to_S3::thread_tmp_188_fu_451_p2() {
    tmp_188_fu_451_p2 = (!ap_const_lv16_1.is_01())? sc_lv<16>(): r_coeffs_q1.read() << (unsigned short)ap_const_lv16_1.to_uint();
}

void poly_Rq_to_S3::thread_tmp_189_fu_457_p1() {
    tmp_189_fu_457_p1 = r_coeffs_q1.read().range(7-1, 0);
}

void poly_Rq_to_S3::thread_tmp_190_fu_469_p1() {
    tmp_190_fu_469_p1 = r_coeffs_q0.read().range(8-1, 0);
}

void poly_Rq_to_S3::thread_tmp_191_fu_473_p1() {
    tmp_191_fu_473_p1 = r_coeffs_q0.read().range(4-1, 0);
}

void poly_Rq_to_S3::thread_tmp_192_fu_477_p1() {
    tmp_192_fu_477_p1 = r_coeffs_q1.read().range(3-1, 0);
}

void poly_Rq_to_S3::thread_tmp_193_fu_489_p1() {
    tmp_193_fu_489_p1 = r_coeffs_q1.read().range(1-1, 0);
}

void poly_Rq_to_S3::thread_tmp_194_fu_501_p1() {
    tmp_194_fu_501_p1 = r_coeffs_q0.read().range(2-1, 0);
}

void poly_Rq_to_S3::thread_tmp_195_fu_693_p3() {
    tmp_195_fu_693_p3 = t_1_fu_687_p2.read().range(2, 2);
}

void poly_Rq_to_S3::thread_tmp_229_i4_cast_fu_557_p1() {
    tmp_229_i4_cast_fu_557_p1 = esl_zext<6,5>(tmp_130_fu_547_p4.read());
}

void poly_Rq_to_S3::thread_tmp_229_i_cast_fu_243_p1() {
    tmp_229_i_cast_fu_243_p1 = esl_zext<6,5>(tmp_121_fu_233_p4.read());
}

void poly_Rq_to_S3::thread_tmp_230_i6_cast_fu_599_p1() {
    tmp_230_i6_cast_fu_599_p1 = esl_zext<6,4>(fold_i5_cast_fu_593_p2.read());
}

void poly_Rq_to_S3::thread_tmp_230_i_cast_fu_281_p1() {
    tmp_230_i_cast_fu_281_p1 = esl_zext<6,4>(fold_i_cast_fu_275_p2.read());
}

void poly_Rq_to_S3::thread_tmp_231_i_cast_fu_291_p4() {
    tmp_231_i_cast_fu_291_p4 = r_4_fu_285_p2.read().range(5, 2);
}

void poly_Rq_to_S3::thread_tmp_232_i1_cast_fu_651_p1() {
    tmp_232_i1_cast_fu_651_p1 = esl_zext<4,2>(fold1_i9_cast_reg_803.read());
}

void poly_Rq_to_S3::thread_tmp_232_i_cast_fu_323_p1() {
    tmp_232_i_cast_fu_323_p1 = esl_zext<4,2>(fold1_i_cast_fu_317_p2.read());
}

void poly_Rq_to_S3::thread_tmp_233_i1_cast_fu_669_p1() {
    tmp_233_i1_cast_fu_669_p1 = esl_zext<3,2>(tmp_131_fu_659_p4.read());
}

void poly_Rq_to_S3::thread_tmp_233_i_cast_fu_359_p1() {
    tmp_233_i_cast_fu_359_p1 = esl_zext<3,2>(tmp_122_reg_774.read());
}

void poly_Rq_to_S3::thread_tmp_234_i1_cast_fu_677_p1() {
    tmp_234_i1_cast_fu_677_p1 = esl_zext<3,2>(fold2_i1_cast_fu_673_p2.read());
}

void poly_Rq_to_S3::thread_tmp_234_i_cast_fu_362_p1() {
    tmp_234_i_cast_fu_362_p1 = esl_zext<3,2>(fold2_i_cast_reg_779.read());
}

void poly_Rq_to_S3::thread_tmp_235_i1_cast_fu_715_p1() {
    tmp_235_i1_cast_fu_715_p1 = esl_zext<16,3>(tmp_235_i1_fu_709_p2.read());
}

void poly_Rq_to_S3::thread_tmp_235_i1_fu_709_p2() {
    tmp_235_i1_fu_709_p2 = (r_10_fu_681_p2.read() & c_8_cast_fu_701_p3.read());
}

void poly_Rq_to_S3::thread_tmp_235_i_cast_fu_399_p1() {
    tmp_235_i_cast_fu_399_p1 = esl_zext<16,3>(tmp_235_i_fu_393_p2.read());
}

void poly_Rq_to_S3::thread_tmp_235_i_fu_393_p2() {
    tmp_235_i_fu_393_p2 = (r_6_fu_365_p2.read() & c_cast_fu_385_p3.read());
}

void poly_Rq_to_S3::thread_tmp_236_i1_cast_cast_fu_725_p3() {
    tmp_236_i1_cast_cast_fu_725_p3 = (!not_tmp_53_i1_fu_719_p2.read()[0].is_01())? sc_lv<3>(): ((not_tmp_53_i1_fu_719_p2.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_0);
}

void poly_Rq_to_S3::thread_tmp_236_i_cast_cast_fu_409_p3() {
    tmp_236_i_cast_cast_fu_409_p3 = (!not_tmp_53_i_fu_403_p2.read()[0].is_01())? sc_lv<3>(): ((not_tmp_53_i_fu_403_p2.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_0);
}

void poly_Rq_to_S3::thread_tmp_237_i1_cast_fu_739_p1() {
    tmp_237_i1_cast_fu_739_p1 = esl_sext<16,3>(tmp_237_i1_fu_733_p2.read());
}

void poly_Rq_to_S3::thread_tmp_237_i1_fu_733_p2() {
    tmp_237_i1_fu_733_p2 = (t_1_fu_687_p2.read() & tmp_236_i1_cast_cast_fu_725_p3.read());
}

void poly_Rq_to_S3::thread_tmp_237_i_cast_fu_423_p1() {
    tmp_237_i_cast_fu_423_p1 = esl_sext<16,3>(tmp_237_i_fu_417_p2.read());
}

void poly_Rq_to_S3::thread_tmp_237_i_fu_417_p2() {
    tmp_237_i_fu_417_p2 = (t_fu_371_p2.read() & tmp_236_i_cast_cast_fu_409_p3.read());
}

void poly_Rq_to_S3::thread_tmp_238_i_fu_427_p2() {
    tmp_238_i_fu_427_p2 = (tmp_235_i_cast_fu_399_p1.read() ^ tmp_237_i_cast_fu_423_p1.read());
}

void poly_Rq_to_S3::thread_tmp_fu_247_p4() {
    tmp_fu_247_p4 = r_coeffs_q0.read().range(11, 8);
}

void poly_Rq_to_S3::thread_tmp_i1_cast_fu_527_p1() {
    tmp_i1_cast_fu_527_p1 = esl_zext<9,8>(tmp_128_fu_517_p4.read());
}

void poly_Rq_to_S3::thread_tmp_i2_cast_fu_531_p1() {
    tmp_i2_cast_fu_531_p1 = esl_zext<9,8>(a_assign_1_cast_fu_511_p2.read());
}

void poly_Rq_to_S3::thread_tmp_i_cast_34_fu_217_p1() {
    tmp_i_cast_34_fu_217_p1 = esl_zext<9,8>(tmp_182_fu_199_p1.read());
}

void poly_Rq_to_S3::thread_tmp_i_cast_fu_213_p1() {
    tmp_i_cast_fu_213_p1 = esl_zext<9,8>(tmp_119_fu_203_p4.read());
}

void poly_Rq_to_S3::thread_tmp_s_fu_163_p1() {
    tmp_s_fu_163_p1 = esl_zext<64,9>(i_reg_129.read());
}

void poly_Rq_to_S3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_151_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_434_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

}

